### ISSUE TITLE
Backends from server-template stuck with old IP/Port if loaded from a server-state file

### ISSUE THREAD

**Issue by madsholden** [haproxy/haproxy#1061]
## Detailed description of the problem

I am using `server-template` with `SRV` records to dynamically set my backend servers, which are registered in Consul. Initially this works well, but after a few redeployments, one of the backends will fail to update the IP address to the new one.

This is the output of `show servers state dob-portal` in various points of time:

After initial deployment. This is the expected output, it gets the correct IP and port from DNS.

```
8 dob-portal 1 portal1 10.48.15.65 2 64 1 1 45 15 3 4 6 0 0 0 0a300f41.addr.payment-development-eu-west-1.consul 24904 _dob-portal-service._tcp.service.consul
8 dob-portal 2 portal2 10.48.12.142 2 64 1 1 45 15 3 4 6 0 0 0 0a300c8e.addr.payment-development-eu-west-1.consul 31351 _dob-portal-service._tcp.service.consul
8 dob-portal 3 portal3 - 0 32 1 1 45 1 0 0 14 0 0 0 - 0 _dob-portal-service._tcp.service.consul
8 dob-portal 4 portal4 - 0 32 1 1 45 1 0 0 14 0 0 0 - 0 _dob-portal-service._tcp.service.consul
```

After one redeployment. I guess this is also expected, the two new backends have been added, and the two old ones are at least unhealthy and in maintenance. I would have expected them to lose the old IP and port, but it works.

```
8 dob-portal 1 portal1 10.48.15.65 0 96 1 1 60 15 3 0 14 0 0 0 - 24904 _dob-portal-service._tcp.service.consul
8 dob-portal 2 portal2 10.48.12.142 0 96 1 1 60 15 3 0 14 0 0 0 - 31351 _dob-portal-service._tcp.service.consul
8 dob-portal 3 portal3 10.48.10.45 2 64 1 1 137 15 3 4 6 0 0 0 0a300a2d.addr.payment-development-eu-west-1.consul 31866 _dob-portal-service._tcp.service.consul
8 dob-portal 4 portal4 10.48.15.65 2 64 1 1 68 15 3 4 6 0 0 0 0a300f41.addr.payment-development-eu-west-1.consul 29310 _dob-portal-service._tcp.service.consul
```

After second redeployment. This is where the problem occurs. The deployment is stuck because the second backend, `portal2` is not healthy. The reason is it's still using the old IP. As you can see, `portal2` and `portal4` have the same hostname, but different IPs.

```
8 dob-portal 1 portal1 10.48.12.142 2 64 1 1 3338 15 3 4 6 0 0 0 0a300c8e.addr.payment-development-eu-west-1.consul 30236 _dob-portal-service._tcp.service.consul
8 dob-portal 2 portal2 10.48.12.142 0 64 1 1 2630 8 2 0 6 0 0 0 0a300f41.addr.payment-development-eu-west-1.consul 31526 _dob-portal-service._tcp.service.consul
8 dob-portal 3 portal3 10.48.10.45 2 64 1 1 3415 15 3 4 6 0 0 0 0a300a2d.addr.payment-development-eu-west-1.consul 31866 _dob-portal-service._tcp.service.consul
8 dob-portal 4 portal4 10.48.15.65 2 64 1 1 3346 15 3 4 6 0 0 0 0a300f41.addr.payment-development-eu-west-1.consul 29310 _dob-portal-service._tcp.service.consul
```

The following is the result of running `dig -p 8600 @127.0.0.1 SRV _dob-portal-service._tcp.service.consul` after the second redeployment:

```
; <<>> DiG 9.16.1-Ubuntu <<>> -p 8600 @127.0.0.1 SRV _dob-portal-service._tcp.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51487
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 9
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_dob-portal-service._tcp.service.consul. IN SRV

;; ANSWER SECTION:
_dob-portal-service._tcp.service.consul. 0 IN SRV 1 1 31866 0a300a2d.addr.payment-development-eu-west-1.consul.
_dob-portal-service._tcp.service.consul. 0 IN SRV 1 1 29310 0a300f41.addr.payment-development-eu-west-1.consul.
_dob-portal-service._tcp.service.consul. 0 IN SRV 1 1 31526 0a300f41.addr.payment-development-eu-west-1.consul.
_dob-portal-service._tcp.service.consul. 0 IN SRV 1 1 30236 0a300c8e.addr.payment-development-eu-west-1.consul.

;; ADDITIONAL SECTION:
0a300a2d.addr.payment-development-eu-west-1.consul. 0 IN A 10.48.10.45
ip-10-48-10-45.node.payment-development-eu-west-1.consul. 0 IN TXT "consul-network-segment="
0a300f41.addr.payment-development-eu-west-1.consul. 0 IN A 10.48.15.65
ip-10-48-15-65.node.payment-development-eu-west-1.consul. 0 IN TXT "consul-network-segment="
0a300f41.addr.payment-development-eu-west-1.consul. 0 IN A 10.48.15.65
ip-10-48-15-65.node.payment-development-eu-west-1.consul. 0 IN TXT "consul-network-segment="
0a300c8e.addr.payment-development-eu-west-1.consul. 0 IN A 10.48.12.142
ip-10-48-12-142.node.payment-development-eu-west-1.consul. 0 IN TXT "consul-network-segment="

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Wed Jan 20 12:47:48 UTC 2021
;; MSG SIZE  rcvd: 607
```

From that output you can see that `portal4` has the correct IP address.

After stopping the old instances, so they don't show up in the SRV record any more, HAProxy actually picks up the correct IP. 

```
8 dob-portal 1 portal1 10.48.12.142 2 64 1 1 7799 15 3 4 6 0 0 0 0a300c8e.addr.payment-development-eu-west-1.consul 30236 _dob-portal-service._tcp.service.consul
8 dob-portal 2 portal2 10.48.15.65 2 64 1 1 12 15 3 4 6 0 0 0 0a300f41.addr.payment-development-eu-west-1.consul 31526 _dob-portal-service._tcp.service.consul
8 dob-portal 3 portal3 10.48.10.45 0 96 1 1 15 15 3 0 14 0 0 0 - 31866 _dob-portal-service._tcp.service.consul
8 dob-portal 4 portal4 10.48.15.65 0 96 1 1 15 15 3 0 14 0 0 0 - 29310 _dob-portal-service._tcp.service.consul
```

It doesn't always do this however, this is after another deployment:

```
8 dob-portal 1 portal1 10.48.12.142 0 96 1 1 19 15 3 0 14 0 0 0 - 30236 _dob-portal-service._tcp.service.consul
8 dob-portal 2 portal2 10.48.15.65 0 96 1 1 19 15 3 0 14 0 0 0 - 31526 _dob-portal-service._tcp.service.consul
8 dob-portal 3 portal3 10.48.10.45 2 64 1 1 1356 15 3 4 6 0 0 0 0a300a2d.addr.payment-development-eu-west-1.consul 21800 _dob-portal-service._tcp.service.consul
8 dob-portal 4 portal4 10.48.15.65 0 64 1 1 65 8 2 0 6 0 0 0 0a300a2d.addr.payment-development-eu-west-1.consul 24000 _dob-portal-service._tcp.service.consul
```

Here it's plain to see that the two running backends have the same hostname, but different IPs.

## Expected behavior

I expect the hostnames to map to the correct IP for all the backends.

## Steps to reproduce the behavior

1. Run haproxy with server-template using SRV records
2. Redeploy service with some overlapping IPs

It is a bit difficult to set up an easy way to reproduce, there are quite a few moving parts to this puzzle. If needed I can try to set something up, let me know.

## Do you have any idea what may have caused this?

It might have something to do with duplicate IP addresses. All my backends are running on one of three different hosts, so there will always be a duplicate when redeploying.

## Do you have an idea how to solve the issue?

I don't know the internals of HAProxy, but it looks reasonable to purge those old backends when they are removed from the DNS entry. Because it only happens when attempting to overwrite an old backend, I believe that would solve the issue.

## What is your configuration?

```
global
    stats socket :9000 mode 660 level admin

defaults
    balance roundrobin

    timeout client 120000ms
    timeout server 120000ms
    timeout connect 5000ms

    mode http
    option forwardfor

    log stdout format raw daemon
    option log-health-checks

frontend shared_alb
    bind :6050

    acl host_portal hdr(host) -i <redacted-hostname>

    use_backend dob-portal if host_portal

    capture request header host len 50
    capture request header user-agent len 250
    capture request header x-amzn-trace-id len 50
    capture request header x-forwarded-for len 80

    log-format '{"service":"haproxy","http_host":"%[capture.req.hdr(0),json(utf8s)]","method":"%HM","path":"%HU","message":"%HM %HU","http_version":"%HV","status_code":"%ST","timestamp":"%t","duration":"%Ta","backend":"%b","backend_ip":"%bi","backend_port":"%bp","alb_ip":"%ci","alb_port":"%cp","frontend":"%f","user_agent":"%[capture.req.hdr(1),json(utf8s)]","request_id":"%[capture.req.hdr(2),json(utf8s)]","client_ip":"%[capture.req.hdr(3),json(utf8s)]"}'

backend dob-portal
    option httpchk GET /td-monitor
    server-template portal 4 _dob-portal-service._tcp.service.consul resolvers consul resolve-opts allow-dup-ip resolve-prefer ipv4 init-addr none check

resolvers consul
    nameserver consul 127.0.0.1:8600
    accepted_payload_size 8192
    hold valid 1s
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Linux 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

`Linux ip-10-48-12-142 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64 GNU/Linux`

## Additional information (if helpful)

HAProxy is running in Docker on Nomad.

**Comment by bdossantos** [comment]
Seem related to https://github.com/haproxy/haproxy/issues/971

**Comment by capflam** [comment]
Recent fixes on the resolvers should fix this issue. A new 2.3 release was emitted. Could you confirm the issue is fixed ?

**Comment by FLavalliere** [comment]
Not sure for my case. Wonder if its maybe allow-dup-ip flag or the fact that i didnt use `hold obsolete 30s`

https://discourse.haproxy.org/t/server-template-still-keeps-out-of-date-server-not-in-srv-any-more/5157/10

**Comment by FLavalliere** [comment]
I'll be adding `hold obsolete 30s` to my setup will see...

**Comment by capflam** [comment]
@FLavalliere, I confirm the issue. When the servers state is loaded from a file, servers inside a server-template with a hostname and an IP addresses but with no entry in the SRV record are never renewed or removed. For now, I don't know how to fix this bug. A workaround is to be sure to have a server-state file matching the current state of the SRV record before reloading HAProxy. It works if the change happens during runtime. But if you save servers state before doing your DNS change, you will hit the bug on reload.

There is no server-state file in the original issue. So it is not the same bug. However, because there was no activity on this issue, I guess we can use it. I'll just update the title.

**Comment by FLavalliere** [comment]
Hello, I was going back to say that indeed the issue is still there with the obsolete flag didnt help anything.

Thanks for reproducing the bug.

**Comment by FLavalliere** [comment]
@capflam indeed this problem seems a bit complex :D

I believe in the server_state.c at line 276 and 255 where it calls the function srv_set_running(srv....)

We will need to relink with the resolution:
resolv_link_resolution(void *requester, int requester_type, int requester_locked);

ie: resolv_link_resolution(srv, OBJ_TYPE_SERVER, 1);


Since in the resolver it looks for : last seen

ie:
```
                 /* Remove obsolete items */
                if (tick_is_lt(tick_add(item->last_seen, resolvers->hold.obsolete), now_ms)) {
```

I'm assuming at reload the resolver / servers entries are not linked......

Though this cannot be as simple as this :D I'll let you guys investigate deeper!.

**Comment by capflam** [comment]
Well, there are several bugs when the state file is loaded at this place. And indeed, it is a little more complex, because if the SRV record is the same, the server is always linked to the corresponding resolution. However, if there is no item referencing this server in the DNS response, there is no way to purge the old IP/Port. It only happens when an existing item is considered as obsolete. Here, we need to add an expiration date on the server itself, using `hold obsolete` value, to clean up the server.

I"ve already the solution to fix this bug. I'm just waiting some other fixes on the resolvers part to work on it. With a bit of luck, It should be fixed the next week.

**Comment by capflam** [comment]
I pushed some fixes in the 2.4 [next](http://git.haproxy.org/?p=haproxy-2.4.git;a=shortlog;h=refs/heads/next) branch:

* [03c6f45ab](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=03c6f45ab) BUG/MINOR: server-state: load SRV resolution only if params match the config
* [e1790c4f2](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=e1790c4f2) BUG/MINOR: server: Forbid to set fqdn on the CLI if SRV resolution is enabled
* [9280d774f](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=9280d774f) BUG/MEDIUM: server/cli: Fix ABBA deadlock when fqdn is set from the CLI
* [56341e0e1](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=56341e0e1) MINOR: resolvers: Clean server in a dedicated function when removing a SRV item
* [f23eed52f](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=f23eed52f) MINOR: resolvers: Remove server from named_servers tree when removing a SRV item
* [30266d821](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=30266d821) BUG/MEDIUM: resolvers: Add a task on servers to check SRV resolution status
* [68d899f9f](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=68d899f9f) BUG/MINOR: resolvers: Use resolver's lock in resolv_srvrq_expire_task() 
* [a701e2221](http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=a701e2221) BUG/MINOR: server/cli: Fix locking in function processing "set server" command

You may test the series on top of the release 2.4.1.

**Comment by FLavalliere** [comment]
Hello @capflam,

Thank you, yes i've seen the commit yesterday on the git.haproxy.org and was happy to see progress on that!

Do you Is the fix part of the following docker? or should I build it ?

docker run -it --rm proxytech/haproxy-ubuntu:2.4.1 haproxy -version

HAProxy version 2.4.1-1ce7d49 2021/06/17 - https://haproxy.org/

**Comment by FLavalliere** [comment]
Ok never mind i've seen as you stated that its part of `http://git.haproxy.org/?p=haproxy-2.4.git;a=shortlog;h=refs/heads/next`

**Comment by FLavalliere** [comment]
Hello,

I've rebuiled it from that GIT NExt branch using the following resulting git hash:

haproxy -v

HAProxy version 2.4.1-a701e2-8 2021/06/18 - https://haproxy.org/

Will see if the issue re-occurs. Though the issue was intermittent. Will keep you posted.

**Comment by capflam** [comment]
Nice, thanks for testing !

**Comment by FLavalliere** [comment]
@capflam  we have been running with the newer version and it seems to be functional.

We had an '5 to 10 minutes' hiccup (our monitoring gave some error's) but by the time we investigate what happened, it was resolved. That being said, I do not beleive the hiccup was caused due to an error in HAProxy.

**Comment by capflam** [comment]
@FLavalliere, thanks ! Based on your feedback, we can consider the issue as solved. Thus I'll merge the series in master soon.

**Comment by FLavalliere** [comment]
Thank you for your work, I can finally sleep at night and not worry about  a  site A giving the content of site B :)

**Comment by FLavalliere** [comment]
@capflam can i send you some files directly for a specific bug related to DNS's and reload ?

Somehow all my backend servers went 'offline' for some reasons and i'm not too sure why.

I've saved some show servers state and other dig elements. I am not sure if its related.

Here somehting that I've noticed:

My server-template is set to have 4 'backend servicse' though somehow the unregistration process did not work properly in consul and I had 6 Backend instead of 3 in the DNS SRV Records.

I've manually unregisted the servicse that didnt unregister properly, returning back to 3 Server-Template.

But even after doing so, it seems like it wasnt getting back to normal on my Failed HAProxy which was giving 503's no services available.

I did some dump of server state before removal and after...

**Comment by capflam** [comment]
Of course, if it is easier for you or because this contains sensitive info, you can send everything to me privately.

**Comment by FLavalliere** [comment]
Question: Upon hot-reload  does it take some times to refresh? We had an occurance after a few deployment of a microservice of a 'wrong' backend being delivered (which is strange as its not even part of that SRV record...). But for a short period of time.

Could it happen when we do a server-state save before hot reloading that the file being saved contains an SRV that match another backend?

Overall the system is way more stable, looks almost all fixed.

**Comment by capflam** [comment]
When HAProxy is started, if a SRV resolution is loaded from a state-file for a given server, HAproxy will wait some time before purging these info, to let the time to receive the first DNS response to refresh the server state. There is no specific timeout for that. `hold timeout` value is used (30s by default). `hold obsolete` cannot be used because it is set to 0 by default.

To avoid this situation, you must take care to have up to date info in the server state file. But I know it is not always possible.

**Comment by capflam** [comment]
Sorry, I closed it too quickly. Fixes are still pending for the 2.2 and 2.0.

**Comment by martinmcnulty** [comment]
I'm seeing what appears to be the same issue with 2.6.22. I saw one instance where all ten of the `server_template` slots ended up taken by zombie servers that were no longer being returned by DNS. I'm trialling a work-around where I filter out any server state entries with failing health checks (`srv_check_result` = `CHK_RES_FAILED` (2)) before sending the reload signal.
