### ISSUE TITLE
DNS-SD in 2.2.10 cycles backends through health states w/o reason

### ISSUE THREAD

**Issue by hynek** [haproxy/haproxy#1160]
Hi, it's me again…I'm sure @bdossantos will join us soon too. ;)

I don't have time for a proper template bug report so real quick:

Updating HAProxy from 2.2.9 to 2.2.10 completely breaks DNS-SD. It seems related to how health checks work, since on each reload of the status page each backend has a different color: green, yellow, brown, or red.

Downgrading back to 2.2.9 fixes it again.

My setup is the same as in #971.

Here's some logs:

<details>

```
Mar  5 12:43:34 c-1fff haproxy[3687545]: [NOTICE] 063/124334 (3687545) : haproxy version is 2.2.10-1ppa1~focal
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 b
ackup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_email-config has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: [NOTICE] 063/124334 (3687545) : path to executable is /usr/sbin/haproxy
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_email-config has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-1 changed its IP from (none) to 10.3.0.88 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-1 changed its IP from (none) to 10.3.0.88 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-1 changed its FQDN from (null) to 0a030058.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-1 changed its FQDN from (null) to 0a030058.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-1 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-1 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-2 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [ALERT] 063/124334 (3687545) : backend 'bk_email-config' has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_email-config/email-config-2 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-2 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-2 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-2 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_email-config/email-config-2 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : bk_email-config/email-config-1 changed its IP from (none) to 10.3.0.88 by DNS additi
onal record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_document-archive/document-archive-1 is going DOWN for maintenance (entry removed from SRV record). 0 active
 and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_email-config/email-config-1 ('0a030058.addr.scaleup.consul') is UP/READY (
resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_document-archive/document-archive-1 is going DOWN for maintenance (entry removed from SRV record). 0 active
 and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_email-config/email-config-2 ('0a03004f.addr.scaleup.consul') is UP/READY (
resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_document-archive has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_email-config/email-config-2 administratively READY thanks to valid DNS ans
wer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_document-archive has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_document-archive/document-archive-1 is going DOWN for maintenance (entry r
emoved from SRV record). 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_document-archive/document-archive-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [ALERT] 063/124334 (3687545) : backend 'bk_document-archive' has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_document-archive/document-archive-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : bk_document-archive/document-archive-1 changed its IP from (none) to 10.3.0.79 by DN
S additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_document-archive/document-archive-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_document-archive/document-archive-1 ('0a03004f.addr.scaleup.consul') is UP
/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_document-archive/document-archive-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_document-archive/document-archive-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_document-archive/document-archive-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_whois_protocol/whois-protocol-3 changed its FQDN from (null) to 0a030050.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_whois_protocol/whois-protocol-3 ('0a030050.addr.scaleup.consul') is UP/REA
DY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_html2pdf-svc/html2pdf-svc-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 b
ackup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_whois_protocol/whois-protocol-3 administratively READY thanks to valid DNS
 answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_html2pdf-svc/html2pdf-svc-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 b
ackup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_html2pdf-svc/html2pdf-svc-1 is going DOWN for maintenance (entry removed f
rom SRV record). 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_html2pdf-svc has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: [ALERT] 063/124334 (3687545) : backend 'bk_html2pdf-svc' has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_html2pdf-svc has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : bk_html2pdf-svc/html2pdf-svc-1 changed its IP from (none) to 10.3.0.79 by DNS additi
onal record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_html2pdf-svc/html2pdf-svc-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_html2pdf-svc/html2pdf-svc-1 ('0a03004f.addr.scaleup.consul') is UP/READY (
resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_html2pdf-svc/html2pdf-svc-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_cdn/cdn-1 is going DOWN for maintenance (entry removed from SRV record). 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_html2pdf-svc/html2pdf-svc-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_cdn/cdn-1 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_html2pdf-svc/html2pdf-svc-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_konto/konto-1 is going DOWN for maintenance (entry removed from SRV record). 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_html2pdf-svc/html2pdf-svc-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_konto/konto-1 ('0a030050.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_html2pdf-svc/html2pdf-svc-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_auth-svc/auth-svc-3 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_cdn/cdn-1 is going DOWN for maintenance (entry removed from SRV record). 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_auth-svc/auth-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_auth-svc/auth-svc-3 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_auth-svc/auth-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_auth-svc/auth-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_whois_protocol/whois-protocol-3 is DOWN, reason: Socket error, check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_whois_protocol/whois-protocol-3 is DOWN, reason: Socket error, check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_whois_protocol/whois-protocol-3 is DOWN, reason: Socket error, check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_spot-svc/spot-svc-3 changed its FQDN from (null) to 0a030058.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_spot-svc/spot-svc-3 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_spot-svc/spot-svc-3 changed its FQDN from (null) to 0a030058.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_spot-svc/spot-svc-3 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_spot-svc/spot-svc-3 ('0a030058.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_spot-svc/spot-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_spot-svc/spot-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_reg-proxy has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: backend bk_reg-proxy has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-1 changed its FQDN from (null) to 0a03004f.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-2 changed its FQDN from (null) to 0a030050.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_spot-svc/spot-svc-3 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_reg-proxy/reg-proxy-2 changed its FQDN from (null) to 0a030050.addr.scaleup.consul by 'SRV record'
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-2 ('0a030050.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-2 ('0a030050.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-2 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_reg-proxy/reg-proxy-2 administratively READY thanks to valid DNS answer.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_reg-proxy/reg-proxy-1 is going DOWN for maintenance (entry removed from SRV record). 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [ALERT] 063/124334 (3687545) : backend 'bk_reg-proxy' has no server available!
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_customer-api/customer-api-1 is going DOWN for maintenance (entry removed from SRV record). 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : bk_reg-proxy/reg-proxy-1 changed its IP from (none) to 10.3.0.79 by DNS additional record.
Mar  5 12:43:34 c-1fff haproxy[3687545]: Server bk_customer-api/customer-api-1 is going DOWN for maintenance (entry removed from SRV record). 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar  5 12:43:34 c-1fff haproxy[3687545]: [WARNING] 063/124334 (3687545) : Server bk_reg-proxy/reg-proxy-1 ('0a03004f.addr.scaleup.consul') is UP/READY (resolves again).
Mar  5 12:43:34 c-1fff haproxy[3687545]: bk_customer-api/customer-api-1 changed its FQDN from (null) to 0a030050.addr.scaleup.consul by 'SRV record'
...
```
</details>

I hope it's somewhat helpful…

**Comment by wtarreau** [comment]
Do you remember which exact version you tested 10 days ago that was still OK ? That could help narrow down the issue to a smaller range.

**Comment by wtarreau** [comment]
I'm seeing only the following commits in 2.2.10 that touch the DNS, in case you can try to revert them in the following order, that could help:
```
a37808290 BUG/MEDIUM: resolvers: Reset server address and port for obselete SRV records
8c0d185e0 BUG/MINOR: resolvers: new callback to properly handle SRV record errors
e2a5b22a3 BUG/MINOR: resolvers: Only renew TTL for SRV records with an additional record
ba216990a BUG/MINOR: resolvers: Fix condition to release received ARs if not assigned
```

**Comment by hynek** [comment]
2.2.9 (`HAProxy version 2.2.9-1ppa1~focal, released 2021/02/06`) _was_ and _is_ OK. A revert to it fixed it immediately.

**Comment by wtarreau** [comment]
Yes, that's what I understood, and is why I asked if we could figure which of the 4 changes affecting the DNS caused this problem. I'm fine if you can't test individual patches, I was just asking, because if one was identified as causing the issue, in the worst case we could start by reverting it in the next release.

**Comment by bdossantos** [comment]
Hello ! On my side the 2.3.5 seem OK (deployed more or less a week ago), but it seem there is a trouble with the 2.3.6 (dns discovery is flapping up/down non stop) :/

**Comment by capflam** [comment]
Thanks for the feedback. Thus there is really a problem with one of these 4 commits. That's not surprising. 2.2.10 and 2.3.6 are shipped with  almost the same commits.

**Comment by wtarreau** [comment]
Makes sense indeed since same fixes were backported to 2.3 and 2.2. @bdossantos do you think you could try to figure which one of the 4 fixes touching the DNS caused this ? For reference the commit IDs in 2.3 are (in reverse apply order, thus in order to try to revert first):
```
$ git log --oneline v2.3.5..v2.3.6 -- src/dns.c
8427aa63d BUG/MEDIUM: resolvers: Reset server address and port for obselete SRV records
826060e38 BUG/MINOR: resolvers: new callback to properly handle SRV record errors
c22e27c37 BUG/MINOR: resolvers: Only renew TTL for SRV records with an additional record
d67f8bb63 BUG/MINOR: resolvers: Fix condition to release received ARs if not assigned
```
I'm fine with reverting the one that causes the trouble. The problem with the DNS is that there's basically no way to fix someone's problem without causing one to someone else. And I'm seriously fed up with this.

**Comment by bedis** [comment]
I think you can remove "8c0d185e0" in 2.2 and "826060e38" in 2.3

**Comment by capflam** [comment]
@bedis, could you explain why this commit is buggy ? Because for me it makes sense. At least for NXDOMAIN status. But also because for a SRV resolution, the requester owner is not a server but a srvrq. Thus `snr_resolution_error_cb()` does nothing.

**Comment by capflam** [comment]
However, because it is a flapping issue, this one is a good suspect :

```
e2a5b22a3 BUG/MINOR: resolvers: Only renew TTL for SRV records with an additional record
```

**Comment by wtarreau** [comment]
Baptiste told me that when dealing with errors from the server he was seeing similar issues with his patch, i.e. too large a response that the server cannot deliver was causing the problem. We'll check this together early next week. @hynek and @bdossantos could maybe revert it from their local tree to confirm, but if we don't see a better solution we'll revert it next week. For the other one you spotted, I don't know :-)

**Comment by capflam** [comment]
I'm fine with that, but we must found a way to expire SRV records on error if we revert this patch. A simple reproducer is to announce SRV records with the associated additional records and few time after, stop announcing anything. All requests ends with a NXDOMAIN response, but nothing is expired.

However, I found something strange with additional records assignment.  I'll try to provide a patch soon. But I'll need some help to verify if it works and most important, if it does not break anything else.

**Comment by wtarreau** [comment]
Maybe the 3 of us can discuss this live on tuesday with a white board and figure a definitive fix ?

**Comment by capflam** [comment]
Yes, it is a good idea :)

**Comment by bedis** [comment]
Hi there, I was in a rush sooner so I could not be much verbose, but now I have some more time :)

Here is what I reproduced very quickly:
- run HAProxy with server-template and a DNS server which returns 3 SRV records
- everything works smoothly
- I add 6 records in the SRV response
- HAProxy increases the "too big" error counter (TODO: need to check if this shouldn't be truncated)
- HAProxy considers the SRV response in error and put all servers in RMAINT
- I remove 6 records from the SRV response
- no servers are recovering from the RMAINT state

I'll dig into that patch during the weekend. Might be missing a flag somewhere or maybe the clean-up is not accurate.

**Comment by capflam** [comment]
Ok @bedis. Thanks for the potential reproducer.

**Comment by bedis** [comment]
@capflam here is the explanation for the "too big" responses.
My dummy DNS server is dumb and just returns corresponding records, whatever the client announces in EDNS extension for payload size. When HAProxy receives a response bigger than the max_accpeted_payload size, it refuses it. This is perfectly normal.

That said, I thought the callback `srvrq_resolution_error_cb()` was a good candidate, but I was wrong actually. I can't reproduce the issue I thought I found on Friday (was a bit in a rush) and what I see now, is that haproxy behaves as expected: when SRV response is on error, all servers are set to MAINT and when the response works again, then some servers recovers.

As a conclusion, I don't have a reproducer yet. I am going to start my consul lab again to try to reproduce.

**Comment by lseelenbinder** [comment]
I have a similar problem due to short TTLs on SRV records. Same behavior, but it seems to be when the records expire before they are refreshed from the primary.

More details on the mailing list here: https://www.mail-archive.com/haproxy@formilux.org/msg39939.html

**Comment by bedis** [comment]
@hynek can you share the configuration for the backend bk_reg-proxy and the resolvers section?

**Comment by bedis** [comment]
@lseelenbinder we don't follow TTLs on DNS, we just "enforce" the "hold" value for various cases.
Could you please share some log lines showing your issue ?

**Comment by bedis** [comment]
So, it seems a37808290d11fa43940b48c81d998448ba0c43e3 in 2.2 is the guilty one. Actually, the IP address memory reset in dns.c is the issue.

**Comment by bedis** [comment]
My point of view is that this part of the code concerns "servers", so it should not be processed in the resolvers / dns layer. We might have to re-architecture this a bit :(

**Comment by lseelenbinder** [comment]
@bedis here's a log (it'll keep doing this every 30-60s on 2.2.10):

```Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : valhalla/valhalla1 changed its IP from :: to 2600:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server valhalla/valhalla1 ('erw-…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server valhalla/valhalla1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver1 changed its IP from :: to 2400:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver1 ('…-dzqlj.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver2 changed its IP from :: to 2400:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver2 ('…-nozqp.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver2 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver3 changed its IP from :: to 2400:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver3 ('…-rnypy.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver3 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver-backup1 changed its IP from :: to 2600:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Backup Server tile_g11/tileserver-backup1 ('…-nunuf.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver-backup1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver-backup3 changed its IP from :: to 2600:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Backup Server tile_g11/tileserver-backup3 ('…-ykcvg.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver-backup3 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : tile_g11/tileserver-backup2 changed its IP from :: to 2600:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Backup Server tile_g11/tileserver-backup2 ('…-vssto.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server tile_g11/tileserver-backup2 administratively READY thanks to valid DNS answer.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : valhalla/valhalla-backup1 changed its IP from :: to 2a01:… by default/g1.
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Backup Server valhalla/valhalla-backup1 ('…-ymlpe.…') is UP/READY (resolves again).
Mar 06 17:53:14 server1 haproxy[29488]: [WARNING] 064/175314 (29490) : Server valhalla/valhalla-backup1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Server tile_g11/tileserver1 is going DOWN for maintenance (No IP for server ). 2 active and 3 backup servers left. 0 sessions active,server1
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Server tile_g11/tileserver2 is going DOWN for maintenance (No IP for server ). 1 active and 3 backup servers left. 0 sessions active,server1
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Server tile_g11/tileserver3 is going DOWN for maintenance (No IP for server ). 0 active and 3 backup servers left. Running on backup. 0 sesserver1queue.
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Server valhalla/valhalla1 is going DOWN for maintenance (No IP for server ). 0 active and 1 backup servers left. Running on backup. 0 sesserver1queue.
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Backup Server tile_g11/tileserver-backup1 is going DOWN for maintenance (No IP for server ). 0 active and 2 backup servers left. Running onserver1 remaining in queue.
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Backup Server tile_g11/tileserver-backup2 is going DOWN for maintenance (No IP for server ). 0 active and 1 backup servers left. Running onserver1 remaining in queue.
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Backup Server tile_g11/tileserver-backup3 is going DOWN for maintenance (No IP for server ). 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar 06 17:53:19 server1 haproxy[29488]: [ALERT] 064/175319 (29490) : backend 'tile_g11' has no server available!
Mar 06 17:53:19 server1 haproxy[29488]: [WARNING] 064/175319 (29490) : Backup Server valhalla/valhalla-backup1 is going DOWN for maintenance (No IP for server ). 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mar 06 17:53:19 server1 haproxy[29488]: [ALERT] 064/175319 (29490) : backend 'valhalla' has no server available!
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : tile_g11/tileserver2 changed its IP from (none) to 2400:… by default/g2.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver2 ('…-nozqp') is UP/READY (resolves again).
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver2 administratively READY thanks to valid DNS answer.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : valhalla/valhalla1 changed its IP from (none) to 2600:… by default/g2.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server valhalla/valhalla1 ('…-zskzu') is UP/READY (resolves again).
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server valhalla/valhalla1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : tile_g11/tileserver1 changed its IP from (none) to 2400:… by default/g2.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver1 ('…-dzqlj') is UP/READY (resolves again).
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver1 administratively READY thanks to valid DNS answer.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : tile_g11/tileserver3 changed its IP from (none) to 2400:… by default/g2.
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver3 ('…-rnypy) is UP/READY (resolves again).
Mar 06 17:53:24 server1 haproxy[29488]: [WARNING] 064/175324 (29490) : Server tile_g11/tileserver3 administratively READY thanks to valid DNS answer.```

**Comment by kaspergrubbe** [comment]
I am seeing the same with 2.2.10 and reverting to 2.2.9 resolves the issue. We're using Consul, `server-template` with SRVs and fairly simple healthchecks:

```
resolvers consuldns
  nameserver consul 127.0.0.1:8600
  accepted_payload_size 8192
  hold valid 5s

backend be_billetto_rails
  mode http
  balance leastconn
  server-template srv 30 _billetto-production-nginx._live.service.consul resolvers consuldns check resolve-opts allow-dup-ip
```

I am trying to be able to replicate this in our test environment.

**Comment by capflam** [comment]
@bedis, a378082 solves a real bug. To my understanding, a server based on SRV records may have a FQDN without IP address but must not have an IP address without a FQDN.

For me there is a deeper problem. First, the loop searching an existing SRV record while we are parsing an additional record is buggy. Thus the TTL of the SRV record is not correctly renewed. The commit a331a1e exposes this bug.

Then, when parsing a SRV response, if a SRV item is found with no additional record assigned, the FQDN is set and a A/AAAA resolution is triggered. But both are not linked. Thus when the server IP is finally set, the TTL of the SRV record is not renewed. And I don't really know what happens when one of them expires. Both must be linked. The requester of the A/AAAA request must be the SRV record request and not the server itself. It should be see as an additional record.

**Comment by hynek** [comment]
> @hynek can you share the configuration for the backend bk_reg-proxy and the resolvers section?

```
resolvers consul
  nameserver consul 127.0.0.1:8600
  accepted_payload_size 8192

# ...

backend bk_reg-proxy
  timeout server 240s

  option httpchk GET /-/lb-heartbeat

  server-template reg-proxy- 3 _reg-proxy-frontend._env-prod.service.consul resolvers consul resolve-opts allow-dup-ip resolve-prefer ipv4 ssl force-tlsv13 allow-0rtt check ca-file vmca.pem

```

**Comment by EmericBr** [comment]
> Maybe the 3 of us can discuss this live on tuesday with a white board and figure a definitive fix ?

I want also participate to this

**Comment by capflam** [comment]
FYI, I pushed a series of patches that fixes several issues. I hope it will work properly in most cases now. But honestly, I will not be surprised if there are still strange bugs. We will emit a 2.3 release next week. Probably Tuesday. We will wait a bit more to release the 2.2.

In addition, we've planned to refactored the resolvers part to make it more maintainable and reliable.

**Comment by sodabrew** [comment]
For those of us following along, should we test 2.4-dev12 to see if it behaves as expected? That is, are you backporting identical patches/behavior from 2.4-dev12 to 2.3 and 2.2 or do you expect enough differences that we have to wait for 2.2.11 to come out before we can confirm whether it works correctly or not?

**Comment by wtarreau** [comment]
If some of you can give it a try, that would be really nice, as it could give us a bit more confidence into the upcoming 2.3.7. And yes, we're backporting fixes as-is (modulo the occasionally required code adaptations). But if 2.4-dev12 still doesn't work for you, there's no way 2.3.7 will ever work, let alone 2.2.11. Many thanks!

**Comment by DvdGiessen** [comment]
FYI, just tested 2.4-dev12, can no longer reproduce this problem. Looks good!

Details: Setup a few Hello World HTTP servers which are discovered by HAProxy through Consul's DNS interface. 2.3.5 worked fine, starting with 2.3.6 if there was more than one server all servers would constantly cycle through health states as they lost and regained a resolved IP. With 2.4dev12, all servers stay up without issues again, there's no unexpected log messages indicating any problem, and also when scaling the number of servers up or down (tested with 1, 4, 8, 16, 24 and 32 instances) I'm not observing any weird behaviour in status.

(Note to others following: Instead of flooding this issue with many "works here too" comments, feel free to leave a thumbs-up reaction on this comment.)

**Comment by wtarreau** [comment]
Many thanks for your detailed tests, Daniël. I feel more confident with an imminent 2.3.7 now :-)

**Comment by capflam** [comment]
FYI, the 2.3.7 is out.

**Comment by lseelenbinder** [comment]
(We're on LTS since these are our production fleet. I'll push the next 2.2 out ASAP after it's released so we can test.)

**Comment by kaspergrubbe** [comment]
Nice work! I can confirm that 2.3.7 fixes the issue for us in our test environment, but we would like to stay on 2.2 for the time being in our production environment so we're ready to test if a pre-release or release happens.

**Comment by wtarreau** [comment]
Thanks for all the great feedback. I can confirm that the intent is to prepare a 2.2 with all this as well. We're just always extra careful with the latest LTS and prefer to emit a 2.3 first to help confirm everything is OK. We've had all we needed here :-)

**Comment by hynek** [comment]
I can confirm that 2.3.7 fixes the problem for me too and since the 2.3 line seems to have access logs again, I'm going to stay on it. (I didn't upgrade before because 2.3.x suddenly hadn't them and I was procrastinating on finding out why.)

**Comment by wtarreau** [comment]
Thanks for your feedback. Anyway fixes will be backported, so 2.2 which is LTS will eventually be fixed once for all.

**Comment by Wicaeed** [comment]
I am still having this in the  fixed versions. I have tested with both the 2.2.9 and 2.3.7 versions.

We have multiple services registered with consul, some with as few as 4 endpoints, and one with 180 endpoints, I stuck all of our services into a single backend to see if this was happening with ALL of them, or only a few.

What I found was that this was not happening for services that had relatively few endpoints registered in Consul ("a few" being under 50), one service with 80 registered endpoints did NOT have this issue, and our largest service with 180 registered endpoints had this issue 100% of the time. The endpoints for this service constantly flap up and down for no reason, and our log is spammed with events similar to those in the Issue

<details>
  <summary>Output of HAProxy 2.3.7:</summary>

```
HA-Proxy version 2.3.7-2d39ce3 2021/03/16 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.7.html
Running on: Linux 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1
  DEBUG   =

Feature list : -EPOLL -KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE -THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IP_FREEBIND
Built without multi-threading support (USE_THREAD not set).
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): no
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```
</details>



<details><summary>HAProxy Config</summary>
<p>

```
global
    log 127.0.0.1 local1
    log 127.0.0.1 local1 notice
    maxconn 1024
    daemon

listen stats
    bind :1936
    mode http
    stats enable
    stats realm Haproxy\ Statistics
    stats show-legends
    stats uri /stats

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server-template service1 4 _www._service1.service.consul. resolvers consul check
    server-template service2 10 _www._service2.service.consul. resolvers consul check
    server-template service3 25 _www._ext.service3.consul. resolvers consul check
    server-template service4 79 _www._service4.service.consul. resolvers consul check
    server-template service5 180 _www._service5.service.consul. resolvers consul check

resolvers consul
  nameserver consul 127.0.0.1:8600
  accepted_payload_size 8192
```
</p>
</details>

Not knowing much about the HAProxy DNS code, how does HAProxy treat DNS SRV requests that are too large to fit into a single UDP request? Could that be causing some issues?

```
~ dig @127.0.0.1 -p 8600 _www._service4.service.consul SRV +short | wc -l
52
~ dig @127.0.0.1 -p 8600 _www._service4.service.consul SRV +short +tcp | wc -l
79
~ dig @127.0.0.1 -p 8600 _www._service5.service.consul SRV +short | wc -l
52
~ dig @127.0.0.1 -p 8600 _www._service5.service.consul SRV +short +tcp | wc -l
180
```

**Comment by lukastribus** [comment]
@Wicaeed that's is not what this issue is about and you are right, this is about going beyond 8192 byte responses. You need DNS discovery via TCP, available only in 2.4-dev.

**Comment by Wicaeed** [comment]
> @Wicaeed that's is not what this issue is about and you are right, this is about going beyond 8192 byte responses. You need DNS discovery via TCP, available only in 2.4-dev.

Thanks for the clarification, I'm already testing it out to see if this will fix our issue :)

**Comment by capflam** [comment]
FYI, 2.2.11 was released with all resolvers fixes. Thanks everyone for your help ! I'm closing the issue now, hopefully for good now.

**Comment by bedis** [comment]
@Wicaeed I think you need to add the "hold obsolete" timer in your resolvers section.
If Consul needs to return more data than what HAProxy can accept, then it may "truncate" the response and just send a chunk of the records. When "hold obsolete" is set to 0s (which is the default), unseen SRV records are immediately cleaned up and associated servers recycled.
If you set "hold obsolete" to 30s, it let enough time (hopefully) for haproxy to refresh each SRV records and avoid recylcing servers too quickly.

Please note that above 100 records will be better supported in 2.4 with DNS over TCP.
Note as well, there is currently a 0^n parsing that may trigger a watchdog when associating SRV records. This also will be fixed in a next release of HAProxy.
