### ISSUE TITLE
Haproxy 2.6.0 unexpected default resolvers

### ISSUE THREAD

**Issue by vooon** [haproxy/haproxy#1740]
### Detailed Description of the Problem

HAProxy fails to start if it cannot connect to resolv.conf resolvers when the config do not have `resolvers` at all.
It looks like if config will have that:
```
resolvers default
  parse-resolv-conf
```

But the config doesn't have it, and do not use name resolution at all.

### Expected Behavior

Not to add unexpected sections and thus not failing because of not met conditions for that items.

### Steps to Reproduce the Behavior

Run haproxy in network namespace, where servers from resolv.conf is not reachable.

### Do you have an idea how to solve the issue?

No, my current workaround simply to add empty `resolvers default` section to the config template.
That makes warning about absence of `namespace`, but at least removes `parse-resolv-conf` behavior.

### What is your configuration?

```haproxy
global
    log         /dev/log local0 debug
    user        neutron
    group       neutron
    maxconn     1024
    pidfile     /var/lib/neutron/external/pids/3963e8f1-5d12-4e92-9640-483ecc72c2da.pid.haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor
    retries                 3
    timeout http-request    30s
    timeout connect         30s
    timeout client          32s
    timeout server          32s
    timeout http-keep-alive 30s

listen listener
    bind 169.254.169.254:80
    server metadata /var/lib/neutron/metadata_proxy
    http-request add-header X-OVN-Network-ID 3963e8f1-5d12-4e92-9640-483ecc72c2da
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.0-a1efc04 2022/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.0.html
Running on: Linux 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-4)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
# ip netns exec ovnmeta-c72dc9a3-610e-45e4-a97f-1ecf8b70f77e haproxy -f /var/lib/neutron/ovn-metadata-proxy/c72dc9a3-610e-45e4-a97f-1ecf8b70f77e.conf
[NOTICE]   (1692444) : haproxy version is 2.6.0-a1efc04
[NOTICE]   (1692444) : path to executable is /sbin/haproxy
[ALERT]    (1692444) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.21'.
[ALERT]    (1692444) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.22'.
[ALERT]    (1692444) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.23'.
[ALERT]    (1692444) : config : Fatal errors found in configuration.
```

**Comment by wtarreau** [comment]
It seems we missed this one, sorry.

It's interesting. That "default" section is automatically created at boot for use by the native HTTP client. I suspect that what is happening is that you probably don't have a `resolv.conf`file in your namespace, and that the section creation fails. If so, this should be changed by making sure that the section is always created, even if empty.

CCing @wlallemand

**Comment by Cherish98** [comment]
> I suspect that what is happening is that you probably don't have a `resolv.conf` file in your namespace, and that the section creation fails.

@wtarreau I suspect not. Instead, haproxy successfully read some DNS servers from `resolv.conf` and tried to connect to those servers, but failed:

https://github.com/haproxy/haproxy/blob/244331f6e7f2f22275cc20eeba2a0c36e27f4e7a/src/resolvers.c#L2511-L2517

-----

You can simply reproduce it with:

```
# ip route add blackhole 1.0.0.0   # so that connect() fails
# echo nameserver 1.0.0.0 >> /etc/resolv.conf   # add a unreachable DNS server
# haproxy -d -f /dev/null

[NOTICE]   (310) : haproxy version is 2.6.0-a1efc04
[NOTICE]   (310) : path to executable is /usr/bin/haproxy
[ALERT]    (310) : config : resolvers 'default': can't connect socket for nameserver '1.0.0.0'.
[ALERT]    (310) : config : Fatal errors found in configuration.
```

-----

I encountered this problem today because I found haproxy failed to start at boot after upgrading to 2.6.0 (I'm using Arch Linux). Probably because systemd started haproxy too early when the DHCP client has not yet set up the routing table but `/etc/resolv.conf` still had old entries. I haven't the foggiest why it is a good idea to test DNS server with `connect()` during startup.

**Comment by wlallemand** [comment]
Looks like a post-parsing error which was not hidden for the httpclient...
The connect() is actually done on the UDP socket just to ensure that the route is available to reach the DNS server.

I'll try to shut the postparsing errors in the case of the httpclient so we don't have to completely disable the httpclient...

**Comment by Cherish98** [comment]
I knew the connect() is done on UDP but still I don't understand why it has to be done at startup, and when it fails why it throws a fatal error and kills the whole haproxy startup.

If I configured a DNS server which was unreachable during startup, but later became reachable after haproxy started, I think that should be a valid configuration. (A warning may be helpful during startup.) Or, to the contrary, if a DNS server were reachable during haproxy startup, and later I deleted its route and it became unreachable, should haproxy throw a fatal error and let the whole process just die immediately? If not, why does reachability-at-startup so important that it can be a fatal error?

**Comment by wlallemand** [comment]
I agree with you on that, in my opinion it shouldn't block at startup. Unfortunately it wasn't designed like that, and people are setting `After=network-online.target` in their unit file to workaround the issue.

The current DNS code has some problems and removing these startup checks would be a good thing but I don't know if that's possible with the current architecture.

**Comment by Cherish98** [comment]
I am using the systemd unit file from Arch Linux which does have `After=network-online.target` set, but apparently I am still getting these errors during startup. In fact systemd restarted haproxy multiple times (spamming system logs with errors), and finally succeed starting haproxy after my DHCP client got DHCPACK and had the routes installed.

**Comment by wlallemand** [comment]
Indeed that won't fix all the issues, the network-online.target doesn't cover every cases :( Honestly I think it even prevent people to write their configuration correctly and to report that kind of problems to the developers.

I checked the code and it's ok to transform the fatal alert into a warning, I pushed the commit c31577f to be backported in 2.6, I'm still looking for a clean way to shut the warning for the default resolver though

**Comment by vooon** [comment]
@wlallemand looks like the fix doesn't work:
```
haproxy version is 2.6.4-2a2078c
[NOTICE]   (2978753) : path to executable is /sbin/haproxy
[WARNING]  (2978753) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.21'.
[WARNING]  (2978753) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.22'.
[WARNING]  (2978753) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.23'.
[ALERT]    (2978753) : config : Fatal errors found in configuration.
```

As you can see it gives warnings but then fails anyway.

**Comment by wlallemand** [comment]
https://github.com/haproxy/haproxy/commit/b10b1196b864b50bb1c781bd0064a1176467046f
https://github.com/haproxy/haproxy/commit/866b88bc95d19c06633fc57a577e5aaf57baf23c
https://github.com/haproxy/haproxy/commit/866b88bc95d19c06633fc57a577e5aaf57baf23c

These patches are also required, it must completely fix the issue..

**Comment by wlallemand** [comment]
You can check with the current 2.6 branch, it includes the patches, they will be in the next minor release (2.6.5)

**Comment by marschro** [comment]
Hi all,
so I still have this issue on 2.8 - How can this be fixed or what config is needed for fixing this?

This is my current haproxy version and OS:
> HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: FreeBSD 13.2-RELEASE-p4 FreeBSD 13.2-RELEASE-p4 GENERIC amd64

- I upgraded from 2.5 sth. 
- I do not use load balancing and never had resolvers configured in the past.
- I was not able to restart ha-Roxy after upgrade because of the above  mentioned errors.

What I did to fix it temporarily and get my servers up and running again was adding a dummy resolver:

```
resolvers default
    nameserver ns1 121.0.0.1:80
```
... of course there is no name server on local at this port... so it probably goes in circles.. ?

Is that an issue or fine?

**Comment by wtarreau** [comment]
Please always report your exact version (haproxy -v) and the output showing the error. It's important as it can help figure what's wrong.

**Comment by marschro** [comment]
> Please always report your exact version (haproxy -v) and the output showing the error. It's important as it can help figure what's wrong.

sorry... totally... updated my post

**Comment by wtarreau** [comment]
So just to make sure, the error you're getting is the same as other users above, i.e.
```
[WARNING]  (2978753) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.23'.
```
?
I'm a bit confused then because this is supposed to be a warning (and granted, no warnings should ever be emitted that cannot be fixed), and the 3 patches above that are supposed to fix it are already part of 2.7 and 2.8, so this would be a
regression between 2.7 and 2.8 maybe ? If so we probably need to reopen it.

**Comment by marschro** [comment]
> So just to make sure, the error you're getting is the same as other users above, i.e.
> 
> ```
> [WARNING]  (2978753) : config : resolvers 'default': can't connect socket for nameserver '192.168.50.23'.
> ```
> 
> ? I'm a bit confused then because this is supposed to be a warning (and granted, no warnings should ever be emitted that cannot be fixed), and the 3 patches above that are supposed to fix it are already part of 2.7 and 2.8, so this would be a regression between 2.7 and 2.8 maybe ? If so we probably need to reopen it.

Yes its the same error message but with an ipv6 address instead of ipv4 mentioned - I have no idea where that comes from.

**Comment by wtarreau** [comment]
OK. If you could try to isolate the smallest reproducer in your config, it would be really appreciated. Also, a copy (possibly anonymized) of your `resolv.conf` would help to understand what corner case managed to slip through the cracks.

**Comment by capflam** [comment]
The 2.8.5 was released. Could you confirm the issue is still there ? However, reading the code, I don't know how it is possible.

**Comment by marschro** [comment]
> OK. If you could try to isolate the smallest reproducer in your config, it would be really appreciated. Also, a copy (possibly anonymized) of your `resolv.conf` would help to understand what corner case managed to slip through the cracks.

Hi,

with this minimal setup, I get the below error:
```yaml
defaults
    mode http
    timeout connect 5s
    timeout client 5s
    timeout server 5s
    timeout tunnel 50s

frontend SSL-Offloading
    bind :80
    bind :443 ssl crt /usr/local/etc/letsencrypt/live/www.devpunx.com/combined.pem alpn h2,http/1.1

    use_backend devpunx if { hdr(host) -i www.devpunx.com }

backend devpunx
    balance roundrobin
    server devpunx 192.168.0.1:80 check
```

Error:
```
  root@dispatcher:~ # haproxy -f /usr/local/etc/haproxy.conf -c
  [NOTICE]   (7808) : haproxy version is 2.8.3-86e043a
  [NOTICE]   (7808) : path to executable is /usr/local/sbin/haproxy
  [ALERT]    (7808) : config : resolvers 'default': can't create socket for nameserver '2001:19f0:300:1704::6'.
  [ALERT]    (7808) : config : Fatal errors found in configuration.
```

probably there is something messed up with my resolve.conf...
I should probably mention, that this only happens within a jail on FreeBSD 13.2 ....

**Comment by wlallemand** [comment]
Okay that's not the same error at all.
This type of errors doesn't seem to be ignored, we'll have to rework the resolvers_finalize_config... :(

**Comment by wlallemand** [comment]
I'll work on a fix, thanks for the report.

**Comment by marschro** [comment]
you are welcome :) always happy to help...

**Comment by Darlelet** [comment]
As for why the error only appears within freebsd jail, perhaps the jail has no ipv6 address configured so `socket(AF_INET6, ...)`  fails in your case.

`domain` argument from `socket(domain, ...)` call is automatically learned from nameserver's entries found in `/etc/resolvers.conf`

https://github.com/haproxy/haproxy/blob/c5bde03a0acac4263b7ff373f819b680d9a52102/src/resolvers.c#L2569-L2571

**Comment by wlallemand** [comment]
The patch above should fix your problem.

**Comment by capflam** [comment]
A fix was provided, I'm closing.
