### ISSUE TITLE
haproxy 2.4 and up: Intermittent: 60 second delay between systemctl stop (or sigterm) and termination when using -Ws or -W

### ISSUE THREAD

**Issue by wiedehopf** [haproxy/haproxy#1841]
### Detailed Description of the Problem

Sometimes after stopping the haproxy service, the program doesn't exit immediately but rather waits 60 seconds before doing so, note the timestamp:
```
Aug 23 08:58:40 test02.mgmt haproxy[46853]: [NOTICE]   (46853) : haproxy version is 2.6.4-2a2078c
Aug 23 08:58:40 test02.mgmt haproxy[46853]: [NOTICE]   (46853) : path to executable is /usr/local/sbin/haproxy
Aug 23 08:58:40 test02.mgmt haproxy[46853]: [WARNING]  (46853) : Exiting Master process...
---- 60 second wait ----
Aug 23 08:59:40 test02.mgmt haproxy[46853]: [ALERT]    (46853) : Current worker (46855) exited with code 143 (Terminated)
Aug 23 08:59:40 test02.mgmt haproxy[46853]: [WARNING]  (46853) : All workers exited. Exiting... (0)
```

Affected versions:
- 2.7-dev4-a8a604-7
- 2.6.4
- 2.4.18

### Expected Behavior

The program should terminate in a timely manner.

### Steps to Reproduce the Behavior

1. nbthreads 2 (edit: now reproduced with 1 thread as well)
2. use a VM with 2 cores
3. run haproxy with -W for example using this simple script:
```
#!/bin/bash

while sleep 0.01; do
  haproxy -W -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
done
```
4a. `kill $(cat /run/haproxy.pid)` and check for termination
4b. or use this terrible bash script: https://gist.github.com/wiedehopf/792aa829d8000acf30a5dad855751fe7 and monitor the output for repeated "wait" output / monitor the output of the loop running haproxy

### Do you have any idea what may have caused this?

Race in worker thread 0:
- signal queue is checked
- SIGTERM is received, the handler puts it into the signal queue
- no further signal queue check
- program calls epoll_wait()

### Do you have an idea how to solve the issue?

Triage in haproxy-2.6.4/src/ev_epoll.c
```
                int timeout = (global.tune.options & GTUNE_BUSY_POLLING) ? 0 : wait_time;

                if (signal_queue_len && tid == 0) {
                        timeout = 0; // triage: make signal / epoll race less likely
                }

                status = epoll_wait(epoll_fd[tid], epoll_events, global.tune.maxpollevents, timeout);
```
This is still a race, but i can't manage to hit, while hitting the earlier race was quite easy (at least on this system, not sure why).
Some testing would suggest it might be good enough, my test has now been through 40000 SIGTERM cycles and i haven't hit the race. Without the triage it would usually be hit by the 10th cycle.

The proper solution would probably be to mask signals, check the signal queue and then wait using epoll_pwait() which will then wake on the signal.
I don't know in regards to epoll_pwait being available on all kernels that have epoll_wait, thus the triage might make the problem less likely. Another option would be an event_fd that can be written to from the signal handler and at the same time can be waited on with epoll_wait, but that got introduced around the same kernel version as epoll_pwait.

And addition safeguard in combination witht he triage might be to reduce the "reaction time" in the case of the race, reducing `#define MAX_DELAY_MS 60000` for `tid == 0` might be an option as well? The commit introducing 60 seconds mentions that waiting only 1 seconds produces significant load using 32 threads, but this change would only impact one thread.

I'm not really familiar with haproxy code so i'm not certain what the repercussions of the above changes would be.

### What is your configuration?

```haproxy
global
  maxconn 10000
  nbthread 2

defaults
  mode http
  timeout connect 5000
  timeout client 5000
  timeout server 5000


frontend stats
  mode http
  bind *:8404
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.4-2a2078c 2022/08/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.4.html
Running on: Linux 5.14.0-70.22.1.el9_0.x86_64 #1 SMP PREEMPT Tue Aug 9 19:45:51 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_STATIC_PCRE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.1 20220127 (Red Hat 11.2.1-9)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

Sending an additional SIGTERM to MAINPID will make haproxy shutdown correctly, here an exaple sending a 2nd SIGTERM after 15 seconds:
```
Aug 23 09:00:53 test02.mgmt haproxy[48003]: [NOTICE]   (48003) : haproxy version is 2.6.4-2a2078c
Aug 23 09:00:53 test02.mgmt haproxy[48003]: [NOTICE]   (48003) : path to executable is /usr/local/sbin/haproxy
Aug 23 09:00:53 test02.mgmt haproxy[48003]: [WARNING]  (48003) : Exiting Master process...
Aug 23 09:01:08 test02.mgmt haproxy[48003]: [ALERT]    (48003) : Current worker (48005) exited with code 143 (Terminated)
Aug 23 09:01:08 test02.mgmt haproxy[48003]: [WARNING]  (48003) : All workers exited. Exiting... (0)
```

--------------------

I've bisected a change in behaviour to this commit: https://github.com/haproxy/haproxy/commit/4f59d386160d645e3b7af990d20c153709787b16

It seems this is not the root cause.
A delay of approximately 1 second is observable on earlier versions (which makes sense considering the 60 second delay in later versions).

Tested on two different systems, could only observe the issue on one of them:
rocky linux 9 was affected.
CentOS 7.9 was not affected. (Edit: managed to reproduce it there as well, seems it's just less likely)

(disregard: This is about as much time i have for the moment, will possibly update this report at a later time, possibly file a bug report with systemd. Yet i don't think i have sufficient understand of how the systemd notify works to file an informed systemd bug currently.)

Edit: After further checking i could reproduce this with just -W, not only with -Ws

Edit2: After some printf debugging it seems that the master sends SIGTERM to the worker process but never gets SIGCHLD after that. Will update further when i figure out where the code for the worker process is.

Edit3: root cause found: epoll_wait / SIGTERM race, see cause / solution sections further up.

**Comment by wlallemand** [comment]
It seems difficult to reproduce and couldn't have the problem for now. 

There is only a signal handler for SIGTERM in the master process, this one will shows the message "Exiting Master process..." which you successfully got before the 60s wait. This signal handler is supposed to send the SIGTERM signal to all the workers, this part is unlikely to be the problem.

Once the worker received the signal it should exit immediately since there is no signal handler there. So like you said in Edit2, the problem seems to be the handling of SIGCHLD in the master. The master is running with only 1 thread, so you must be able to reproduce with any number of threads in your configuration.

The master is not doing much, so I suppose, the master was stuck in epoll_wait() and interrupted by a EINTR... but the signal_queue_len check is supposed to break the loop once there. So... I don't see any problem in the code for now but I might be missing something.

You could try to add some printf in the _do_poll function to check the value of signal_queue_len, I'll try to figure out a way to reproduce.

**Comment by wiedehopf** [comment]
I've revised the printf stuff i had in there and hope you can use the output.

Log with the issue:
```
[2022-09-08 05:54:43.095849]Run 21: starting haproxy
[2022-09-08 05:54:43.095887]---------------------------------------------------
[2022-09-08 05:54:43.099906]Using epoll() as the polling mechanism.
[2022-09-08 05:54:43.099958][NOTICE]   (3975454) : New worker (3975459) forked
[2022-09-08 05:54:43.099974][NOTICE]   (3975454) : Loading success.
[2022-09-08 05:54:43.100581][ALERT]    (3975459) : start poll loop
[2022-09-08 05:54:43.100984][NOTICE]   (3975459) : run_poll_loop() tid 0: checked signal queue, was zero.
[2022-09-08 05:54:43.101016][NOTICE]   (3975459) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.101070][NOTICE]   (3975459) : _do_poll() calling epoll_wait tid: 1 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.102201]Using epoll() as the polling mechanism.
[2022-09-08 05:54:43.102330][NOTICE]   (3975454) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:54:43.102416][NOTICE]   (3975454) : run_poll_loop() tid 0: checked signal queue, was zero.
[2022-09-08 05:54:43.102466][NOTICE]   (3975454) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.104366][NOTICE]   (3975454) : signal_handler() called with sig: 15
[2022-09-08 05:54:43.104416][NOTICE]   (3975454) : _do_poll() tid: 0 status epoll_wait: -1
[2022-09-08 05:54:43.104450][NOTICE]   (3975454) : __signal_process_queue(): blocked signals
[2022-09-08 05:54:43.104480][NOTICE]   (3975454) : haproxy version is 2.6.4-2a2078c
[2022-09-08 05:54:43.104506][NOTICE]   (3975454) : path to executable is /usr/local/sbin/haproxy
[2022-09-08 05:54:43.104532][WARNING]  (3975454) : Exiting Master process...
[2022-09-08 05:54:43.104558][NOTICE]   (3975454) : mworker_kill(): kill pid 3975459 sig 15
[2022-09-08 05:54:43.104849][NOTICE]   (3975454) : __signal_process_queue(): will now unblock signals
[2022-09-08 05:54:43.104894][NOTICE]   (3975454) : signal_handler() called with sig: 17
[2022-09-08 05:54:43.104927][NOTICE]   (3975454) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 1 wake: 0
[2022-09-08 05:55:43.165164][NOTICE]   (3975454) : _do_poll() tid: 0 status epoll_wait: 0
[2022-09-08 05:55:43.165248][NOTICE]   (3975454) : __signal_process_queue(): blocked signals
[2022-09-08 05:55:43.165269][NOTICE]   (3975454) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:55:43.165284][ALERT]    (3975454) : Current worker (3975459) exited with code 143 (Terminated)
[2022-09-08 05:55:43.165298][NOTICE]   (3975454) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:55:43.165311][WARNING]  (3975454) : All workers exited. Exiting... (0)
[2022-09-08 05:55:43.165878]---------------------------------------------------
[2022-09-08 05:55:43.165962]Run 21: exited
```

I'll try and describe the events as i understand them:
- haproxy gets SIGTERM (15)
- master prints "Exiting master process"
- master sends SIGTERM (15) to worker process
- master receives SIGCHLD (17)
- master enters epoll_wait
- master wakes up after 60 seconds
- master processes signals
- master exits


So ... it's a race in the master and not a race in the worker as i previously thought.
Another red herring and that after all the edits, sorry.

> The master is not doing much, so I suppose, the master was stuck in epoll_wait() and interrupted by a EINTR... but the signal_queue_len check is supposed to break the loop once there. So... I don't see any problem in the code for now but I might be missing something.

It breaks the loop only after the epoll_wait is done, which can take 60 seconds.
Now my race is fixed by just adding an extra check before epoll_wait.
(you still have a very short race window as the you can have a signal between checking the signal queue and entering the system call)

Just for comparison a log with the same outputs when the race doesn't happen:
```
[2022-09-08 05:54:43.085287]Run 20: starting haproxy
[2022-09-08 05:54:43.085352]---------------------------------------------------
[2022-09-08 05:54:43.090500]Using epoll() as the polling mechanism.
[2022-09-08 05:54:43.090557][NOTICE]   (3975439) : New worker (3975445) forked
[2022-09-08 05:54:43.090574][NOTICE]   (3975439) : Loading success.
[2022-09-08 05:54:43.091693]Using epoll() as the polling mechanism.
[2022-09-08 05:54:43.091730][NOTICE]   (3975439) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:54:43.091746][NOTICE]   (3975439) : run_poll_loop() tid 0: checked signal queue, was zero.
[2022-09-08 05:54:43.091780][NOTICE]   (3975439) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.092168][ALERT]    (3975445) : start poll loop
[2022-09-08 05:54:43.092694][NOTICE]   (3975445) : run_poll_loop() tid 0: checked signal queue, was zero.
[2022-09-08 05:54:43.092740][NOTICE]   (3975445) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.092940][NOTICE]   (3975439) : signal_handler() called with sig: 15
[2022-09-08 05:54:43.092988][NOTICE]   (3975439) : _do_poll() tid: 0 status epoll_wait: -1
[2022-09-08 05:54:43.093017][NOTICE]   (3975439) : __signal_process_queue(): blocked signals
[2022-09-08 05:54:43.093043][NOTICE]   (3975439) : haproxy version is 2.6.4-2a2078c
[2022-09-08 05:54:43.093067][NOTICE]   (3975439) : path to executable is /usr/local/sbin/haproxy
[2022-09-08 05:54:43.093091][WARNING]  (3975439) : Exiting Master process...
[2022-09-08 05:54:43.093119][NOTICE]   (3975439) : mworker_kill(): kill pid 3975445 sig 15
[2022-09-08 05:54:43.093144][NOTICE]   (3975439) : __signal_process_queue(): will now unblock signals
[2022-09-08 05:54:43.093168][NOTICE]   (3975439) : _do_poll() calling epoll_wait tid: 0 signal_queue_len: 0 wake: 0
[2022-09-08 05:54:43.093789][NOTICE]   (3975439) : signal_handler() called with sig: 17
[2022-09-08 05:54:43.093828][NOTICE]   (3975439) : _do_poll() tid: 0 status epoll_wait: -1
[2022-09-08 05:54:43.093845][NOTICE]   (3975439) : __signal_process_queue(): blocked signals
[2022-09-08 05:54:43.093869][NOTICE]   (3975439) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:54:43.093884][ALERT]    (3975439) : Current worker (3975445) exited with code 143 (Terminated)
[2022-09-08 05:54:43.093897][NOTICE]   (3975439) : mworker_catch_sigchld() calling waitpid
[2022-09-08 05:54:43.093911][WARNING]  (3975439) : All workers exited. Exiting... (0)
[2022-09-08 05:54:43.094201]---------------------------------------------------
[2022-09-08 05:54:43.094249]Run 20: exited
```

And the shell scripts with shorter sleeps to run haproxy and also send sigterm i used for the above output if you need those.
https://gist.github.com/wiedehopf/5acf36348de5de1941ea93c3269e0e70

If you have trouble reproducing, i'd suggest adding a sleep at the start of _do_poll, that should make the race window much longer.

**Comment by wlallemand** [comment]
I think your analyze is right and your patch proposal might be a good solution. I couldn't find a change of the wait_time based on signal_queue_len, so if you trigger the SIGCHLD before entering epoll_wait, epoll_wait won't be stopped by EINTR and will keep the default 60s timeout...

**Comment by wlallemand** [comment]
@wiedehopf this patch should fix your issue, it will be backported in every stable branches.

**Comment by wiedehopf** [comment]
Thank you.
Unfortunately i'm still able to hit the race, at greatly reduced frequency though:
```
[2022-09-08 11:00:07.907119]Run 1510: starting haproxy
[2022-09-08 11:00:07.907156]---------------------------------------------------
[2022-09-08 11:00:07.910569][NOTICE]   (3643626) : New worker (3643631) forked
[2022-09-08 11:00:07.910604][NOTICE]   (3643626) : Loading success.
[2022-09-08 11:00:07.914855][NOTICE]   (3643626) : haproxy version is 2.7-dev5-3dd79d-50
[2022-09-08 11:00:07.914889][NOTICE]   (3643626) : path to executable is /usr/local/sbin/haproxy
[2022-09-08 11:00:07.914904][WARNING]  (3643626) : Exiting Master process...
-- 60 seconds pass --
[2022-09-08 11:01:07.976068][ALERT]    (3643626) : Current worker (3643631) exited with code 143 (Terminated)
[2022-09-08 11:01:07.976211][WARNING]  (3643626) : All workers exited. Exiting... (0)
[2022-09-08 11:01:07.976480]---------------------------------------------------
[2022-09-08 11:01:07.976516]Run 1510: exited
```

Placing the check after
```
        clock_entering_poll();
```
makes it yet that much harder to hit the race.

I've patched the current dev version locally and will see if i can still hit the race (currently at 85000 iterations and have yet to hit it).

Now apparently no one else is hitting this bug, but it has the potential to result in haproxy being unavailable for 60 seconds instead of the expected 0.1 seconds or so a restart usually takes.
I can just patch it locally when building for my purposes so i'm not really concerned, but in case you want to go for the short race window which i've yet to hit, this is the change i made on top of the current state:
```
diff --git a/src/ev_epoll.c b/src/ev_epoll.c
index 746a0d1..b4c2f6c 100644
--- a/src/ev_epoll.c
+++ b/src/ev_epoll.c
@@ -225,8 +225,9 @@ static void _do_poll(struct poller *p, int exp, int wake)
        /* Now let's wait for polled events.
         * Check if the signal queue is not empty in case we received a signal
         * before entering the loop, so we don't wait MAX_DELAY_MS for nothing */
-       wait_time = (wake | signal_queue_len) ? 0 : compute_poll_timeout(exp);
+       wait_time = wake ? 0 : compute_poll_timeout(exp);
        clock_entering_poll();
+       wait_time = signal_queue_len ? 0 : wait_time;
        do {
                int timeout = (global.tune.options & GTUNE_BUSY_POLLING) ? 0 : wait_time;
 ```

**Comment by wtarreau** [comment]
Now I'm concerned, because we suspected that maybe the signal was delivered during the boot sequence and was missed before the first poll, but your patch indicates that it can also be delivered during clock_entering_poll(), which makes me think that it's not blocked as it should be. But if signals were not correctly blocked we'd still get all the massive trouble we used to get in the past (before threads and during early threads).

One thing I'm wondering is if we're properly blocking signals in the master in wait mode. Maybe that call path was overlooked, and it could explain a lot of things. That part is a mess (like everywhere signals are dealt with), I'm already feeling sick just at the idea of having to look at that again :-(

**Comment by wiedehopf** [comment]
> your patch indicates that it can also be delivered during clock_entering_poll()
It seems very clear to me they can be.

If the signals would be blocked during clock_entering_poll(), they would need to be unblocked before epoll_wait().
Otherwise the wait could not be interrupted by signals.

There is no such unblocking between clock_entering_poll() and epoll_wait().

Checking if the signals are blocked indicates they are indeed not blocked:
```
[2022-09-08 12:18:08.446349][NOTICE]   (1033815) : New worker (1033817) forked
[2022-09-08 12:18:08.446402][NOTICE]   (1033815) : Loading success.
[2022-09-08 12:18:08.446418][NOTICE]   (1033815) : mworker_reexec_waitmode()
[...]
[2022-09-08 12:18:08.448721][NOTICE]   (1033815) : _do_poll(): SIGTERM blocked: 0
[2022-09-08 12:18:08.448759][NOTICE]   (1033815) : _do_poll(): SIGCHLD blocked: 0
[...]
[2022-09-08 12:19:08.492378][NOTICE]   (1033815) : _do_poll(): SIGTERM blocked: 0
[2022-09-08 12:19:08.492400][NOTICE]   (1033815) : _do_poll(): SIGCHLD blocked: 0
```
Obtained with these changes in _do_poll():
```
    thread_harmless_now();

    sigset_t oldset;                                                                                                                                                                           
    sigprocmask(SIG_BLOCK, &oldset, NULL);
    ha_notice("_do_poll(): SIGTERM blocked: %d\n", sigismember(&oldset, SIGTERM));
    ha_notice("_do_poll(): SIGCHLD blocked: %d\n", sigismember(&oldset, SIGCHLD));

    /* Now let's wait for polled events.
```

My patch only reduces the race window anyhow.
Signals can't be blocked during epoll_wait(), otherwise signals won't be able to interrupt it.

I'm not sure how the race can be completely avoided without a different system call like epoll_pwait():
- block signals
- check signal_queue_len
- epoll_pwait() (unblocks signals and enters epoll_wai atomically)

But:
> epoll_pwait() was added to Linux in kernel 2.6.19.  Library support is provided in glibc starting with version 2.6.
It's old enough but worth mentioning that epoll_wait was introduced a bit earlier.

Please do tell me to shut up if you don't want my input on this :). Otherwise i'm happy to help.

**Comment by wtarreau** [comment]
Yes of course you're right, my apologizes, I'm always confused about that area that I avoid like the flea due to the numerous bugs we've faced every time we touched it. What we have asynchronous now is only the signal delivery to the handlers, which solved most of our trouble.

While I do know about epoll_pwait() and friends, I don't want to rely on it for the reasons you mentioned plus the fact that we don't just deal with linux, we also have other OSes without equivalents (e.g. what's the equivalent in solaris with evport, I don't know). Instead since we're not relying on high frequency signals, I'd rather go back to the more classical self-wake that we can  easily achieve with this, in case you want to test:
```
--- a/src/signal.c
+++ b/src/signal.c
@@ -56,6 +56,8 @@ void signal_handler(int sig)
        signal_state[sig].count++;
        if (sig)
                signal(sig, signal_handler); /* re-arm signal */
+       /* in case we're about to sleep in the poller */
+       wake_thread(tid);
 }
 
 /* Call handlers of all pending signals and clear counts and queue length. The
```

**Comment by wiedehopf** [comment]
Applying that diff (wake_thread) to current dev seems to stop the race so far (56000 iterations and counting).

It requires 43c891dda0c7c1c9f12dab5b77ac20b158a68adc though, without it, i could observe the race on run 880.
I suppose that makes sense considering TH_FL_SLEEPING is set after the signal_queue_len check in run_poll_loop().

**Comment by wtarreau** [comment]
Thanks a lot for testing and confirming, at least it completely makes sense. And indeed it couldn't work without the already merged patch. We're going to merge it and mark it for backports.

**Comment by wiedehopf** [comment]
If i'm not mistaken, instead of checking in 4 different pollers (43c891dda0c7c1c9f12dab5b77ac20b158a68adc), it would be sufficient to check in run_poll_loop() after TH_FL_SLEEPING has been set?
Like this:
```diff
diff --git a/src/haproxy.c b/src/haproxy.c
index 2eb84bd..b0f7ce9 100644
--- a/src/haproxy.c
+++ b/src/haproxy.c
@@ -2818,7 +2818,7 @@ void run_poll_loop()
                        _HA_ATOMIC_OR(&th_ctx->flags, TH_FL_SLEEPING);
                        _HA_ATOMIC_AND(&th_ctx->flags, ~TH_FL_NOTIFIED);
                        __ha_barrier_atomic_store();
-                       if (thread_has_tasks()) {
+                       if (thread_has_tasks() || signal_queue_len) {
                                activity[tid].wake_tasks++;
                                _HA_ATOMIC_AND(&th_ctx->flags, ~TH_FL_SLEEPING);
                        } else
diff --git a/src/signal.c b/src/signal.c
```

I've reverted 43c891dda0c7c1c9f12dab5b77ac20b158a68adc locally, applied that diff above (plus wake_thread in the signal handler) and after 82000 cycles no race so far.
That is the logical position in the code to me, but i might be missing something.

I suppose that poller_wr_pipe is haproxys POSIX compliant version of event_fd, fancy.

No more race, thanks a lot for taking the time!

**Comment by wtarreau** [comment]
Hmmm 4 pollers ? We have 5. Ah, unfortunately select() passed through the cracks, we'll have to fix it.

But yes, as I told William, I initially thought the test was already performed in the loop itself and that it used to set the wake flag, until I saw that we were purging those events early in the loop and revised my analysis.

Your proposal would partially be OK however we'd need to do at an other place, e.g. in the `if (!wake)` part, that is already located after the moment the TH_FL_SLEEPING flag is set, because in its current form it would incorrectly report task wakeups in the activity stats (no big deal but they're used for debugging).

And in this case I agree that it would be more durable than the current fix.

**Comment by wiedehopf** [comment]
This also hits on my slight confusion on sometimes checking tid == 0 when checking signals_queue_len and not checking it in the poller.
We only need to wake on signals_queue_len with tid == 0, correct?

How about this:
```c        /* expire immediately if events or signals are pending */                                                                                                                              
        wake = 1;
        if (thread_has_tasks())
            activity[tid].wake_tasks++;
        else {
            _HA_ATOMIC_OR(&th_ctx->flags, TH_FL_SLEEPING);
            _HA_ATOMIC_AND(&th_ctx->flags, ~TH_FL_NOTIFIED);
            __ha_barrier_atomic_store();
            if (thread_has_tasks()) {
                activity[tid].wake_tasks++;
                _HA_ATOMIC_AND(&th_ctx->flags, ~TH_FL_SLEEPING);
            } else if (signal_queue_len && tid == 0) {
                _HA_ATOMIC_AND(&th_ctx->flags, ~TH_FL_SLEEPING);
            } else {
                wake = 0;
            }
        }
```

Together with using wake_thread(), that should mean all signal_queue_len checks can be removed from every poller.
That way all of the signals_queue_len logic is kept in the run_poll_loop(), making it more robust than having some checks in the pollers.

**Comment by wtarreau** [comment]
No, not just tid==0 because there's the special case of the (rare) inter-thread signal delivery for the watchdog/panic events via pthread_kill(). Better just don't add antoher special case there.

However I do agree with removing the check from the pollers to keep it more robust (especially since we saw that it was easy to miss one poller).

Do you want to contribute a patch with what's above ?

**Comment by wiedehopf** [comment]
Sure, will draft a patch and post here.

**Comment by wiedehopf** [comment]
Patch draft: https://github.com/wiedehopf/haproxy/commit/8220d0b01d2e28d388ca531b37d82cfa1d0136f7

Tested for the race using epoll, poll and select. After 10000 cycles each, no race.
Though testing for race conditions is ... racy, thus checked only because it's easy to do.
I'm happy with the logic now making the race impossible.

Should i make it a PR so the bot will send it to the mailing list?

**Comment by wtarreau** [comment]
Great. I'm fine with this (and the description). @wlallemand is that OK for you as well ?
If so I can take it from here now that it was created, no need to repost somewhere else.

**Comment by wlallemand** [comment]
Looks good to me!

**Comment by wtarreau** [comment]
Perfect, now merged, thank you guys for this great work!

**Comment by wiedehopf** [comment]
Just out of curiosity in regards to backporting, it seems 1.8 has a very very different layout and does not have wake_thread().
With the 1 second max delay before processing the signal prior to 2.4 .... this might not be critical. For 1.8 it would need a completely different patch.

Also for 1.8 i can't hit the race ... not that it means too much (running without -S as 1.8 didn't have that).

Up from 2.0 hitting the race is easy. Backporting up from 2.0 seemed very straight forward so not an issue.

I only added "all stable branches" because the previous patch meant to fix this issue had that.
But as with 1 second delay this issue doesn't seem to qualify as critical, no backport to 1.8 might be the better choice.


Unrelated: noticed i have a typo in one comment in my patch, extra s in wake_thread().

**Comment by wtarreau** [comment]
Yeah I think that in 1.8 we didn't have inter-task wakeups and that even dealing with the queue was a big mess. I don't remember how we did it by then but it was a pain.

Ah just found, in 1.8 we call THREAD_WANT_SYNC(), which basically wakes every thread up. But I do generally agree, nobody ever complained about this 1-second delay in 1.8, there's no point risking to break it in its last months for this. Thus I agree with you that 2.0 should be the ultimate target.

Regarding the typo... too late :-)  You're not the first one nor the last one, no worries, and no need to send a fix just for this, The intent and explanation are correct in the comment, that's what really matters.

**Comment by Darlelet** [comment]
Sorry to resurrect this old thread, but I wanted to document a minor behavior regression that could be observed with versions < 2.7 where the above fix (eea152e) was backported:

When reloading haproxy (in master-worker mode), by sending `SIGUSR2` on the master process for example, we can observe a garbage `c` character on the process output from time to time (again, this can only be observed in versions below 2.7 where eea152e was backported):

```
[NOTICE]   (235737) : haproxy version is 2.6.5-4a1f70-33
[NOTICE]   (235737) : path to executable is /tmp/haproxy-2.6/haproxy
[WARNING]  (235737) : config : ca-file: 0 CA were loaded from '@system-ca'
[NOTICE]   (235737) : New worker (235739) forked
[NOTICE]   (235737) : Loading success.
[NOTICE]   (235737) : Reloading HAProxy
[NOTICE]   (235737) : haproxy version is 2.6.5-4a1f70-33
[NOTICE]   (235737) : path to executable is /tmp/haproxy-2.6/haproxy
[WARNING]  (235737) : config : ca-file: 0 CA were loaded from '@system-ca'
[NOTICE]   (235737) : New worker (235757) forked
[NOTICE]   (235737) : Loading success.
[WARNING]  (235739) : Proxy stats stopped (cumulated conns: FE: 0, BE: 0).
c[NOTICE]   (235737) : haproxy version is 2.6.5-4a1f70-33 ------ Notice the extra 'c' at the start of the line
[NOTICE]   (235737) : path to executable is /tmp/haproxy-2.6/haproxy
[WARNING]  (235737) : Former worker (235739) exited with code 0 (Exit)
```

When stracing the process, we can see that this is emitted by the master process:
```
strace: Process 235637 attached
[pid 235637] +++ exited with 0 +++
write(2, "[NOTICE]   (235636) : haproxy ve"..., 57[NOTICE]   (235636) : haproxy version is 2.6.5-4a1f70-33
) = 57
write(2, "[NOTICE]   (235636) : path to ex"..., 69[NOTICE]   (235636) : path to executable is /tmp/haproxy-2.6/haproxy
) = 69
write(2, "[WARNING]  (235636) : config : c"..., 75[WARNING]  (235636) : config : ca-file: 0 CA were loaded from '@system-ca'
) = 75
strace: Process 235638 attached
[pid 235636] write(2, "[NOTICE]   (235636) : New worker"..., 49[NOTICE]   (235636) : New worker (235638) forked
) = 49
[pid 235636] write(2, "[NOTICE]   (235636) : Loading su"..., 39[NOTICE]   (235636) : Loading success.
) = 39
strace: Process 235639 attached
strace: Process 235640 attached
[pid 235640] +++ exited with 0 +++
[pid 235636] --- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=204721, si_uid=1000} ---
[pid 235638] --- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=204721, si_uid=1000} ---
[pid 235636] write(6, "c", 1)           = 1
[pid 235636] write(2, "[NOTICE]   (235636) : Reloading "..., 40[NOTICE]   (235636) : Reloading HAProxy
) = 40
strace: Process 235655 attached
[pid 235655] +++ exited with 0 +++
[pid 235636] write(2, "[NOTICE]   (235636) : haproxy ve"..., 57[NOTICE]   (235636) : haproxy version is 2.6.5-4a1f70-33
) = 57
[pid 235636] write(2, "[NOTICE]   (235636) : path to ex"..., 69[NOTICE]   (235636) : path to executable is /tmp/haproxy-2.6/haproxy
) = 69
[pid 235636] write(2, "[WARNING]  (235636) : config : c"..., 75[WARNING]  (235636) : config : ca-file: 0 CA were loaded from '@system-ca'
) = 75
[pid 235639] write(8, "c", 1)           = 1
[pid 235638] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=235636, si_uid=1000} ---
[pid 235638] write(8, "c", 1)           = 1
strace: Process 235673 attached
[pid 235636] write(2, "[NOTICE]   (235636) : New worker"..., 49[NOTICE]   (235636) : New worker (235673) forked
) = 49
[pid 235636] write(2, "[NOTICE]   (235636) : Loading su"..., 39[NOTICE]   (235636) : Loading success.
) = 39
[pid 235638] write(2, "[WARNING]  (235638) : Proxy stat"..., 75[WARNING]  (235638) : Proxy stats stopped (cumulated conns: FE: 0, BE: 0).
) = 75
[pid 235638] write(8, "c", 1)           = 1
[pid 235638] write(10, "c", 1)          = 1
[pid 235639] write(8, "c", 1)           = 1
[pid 235638] write(10, "c", 1)          = -1 EBADF (Bad file descriptor)
[pid 235639] +++ exited with 0 +++
[pid 235638] +++ exited with 0 +++
strace: Process 235675 attached
[pid 235636] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=235638, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
##################################################
[pid 235636] write(0, "c", 1c)           = 1                ------- HERE -> 'c' char is written to fd:0
##################################################
[pid 235636] write(2, "[NOTICE]   (235636) : haproxy ve"..., 57[NOTICE]   (235636) : haproxy version is 2.6.5-4a1f70-33
) = 57
[pid 235636] write(2, "[NOTICE]   (235636) : path to ex"..., 69[NOTICE]   (235636) : path to executable is /tmp/haproxy-2.6/haproxy
) = 69
[pid 235636] write(2, "[WARNING]  (235636) : Former wor"..., 71[WARNING]  (235636) : Former worker (235638) exited with code 0 (Exit)
) = 71
[pid 235675] +++ exited with 0 +++
strace: Process 235676 attached
```
What causes this `c` char to be printed turns out to be `wake_thread()` from `signal_handler()` called from the parent process (this call was added in eea152e): in this case it seems that the poller array may not be initialized yet, causing `poller_wr_pipe[thr]` to resolve to 0 (default value from static array `int poller_wr_pipe[MAX_THREADS]`). Which means we're actually writing `c` char on stdin.

Since f3efef4d60 (starting with 2.7), the issue cannot be reproduced because a check was added to `wake_thread()`, and in this specific case it prevents `wake_thread()` from writing on the uninitialized wr_pipe fd.

For versions < 2.7 (lacking f3efef4d60), manually guarding `wake_thread()` call in `signal_handler()` to mimic what's done with f3efef4d60 seems to do the trick to restore consistency with 2.7+ versions.

```diff
diff --git a/src/signal.c b/src/signal.c
index 3d7a9a898..b516da46f 100644
--- a/src/signal.c
+++ b/src/signal.c
@@ -58,7 +58,10 @@ void signal_handler(int sig)
                signal(sig, signal_handler); /* re-arm signal */
 
        /* If the thread is TH_FL_SLEEPING we need to wake it */
-       wake_thread(tid);
+       if (sleeping_thread_mask & tid_bit) {
+               _HA_ATOMIC_AND(&sleeping_thread_mask, ~tid_bit);
+               wake_thread(tid);
+       }
 }
 
 /* Call handlers of all pending signals and clear counts and queue length. The
```

Now I can't tell if it's relevant or not to consider this "fix" for impacted versions, but for anyone interested, at least it's documented there (before I actually forget it) :)
