### ISSUE TITLE
2.0.3: "do-resolve" eats up memory

### ISSUE THREAD

**Issue by pyhd** [haproxy/haproxy#222]
```
frontend fe
    bind 10.0.0.1:443
    bind 10.0.0.1:4443 transparent
    mode tcp
    tcp-request inspect-delay 2s
    stick-table type binary len 32 size 100k expire 2h
    tcp-request content track-sc1 payload_lv(43,1) if { req.ssl_sni,lower -m found }
    tcp-request content do-resolve(txn.myip,mydns,ipv4) req.ssl_sni,lower if { req.ssl_sni,lower -m found }
    default_backend be

backend be
    mode tcp
    tcp-request content reject if { var(txn.myip) -m ip 127.0.0.0/8 10.0.0.0/8 }
    tcp-request content set-dst var(txn.myip)
    server clear 0.0.0.0:0
```

As I checked within `show pools` after hours:
```
  - Pool dns_resolut (480 bytes) : 5 allocated (2400 bytes), 4 used, 0 failures, 1 users, @0x8be0c0=07 [SHARED]
  - Pool dns_answer_ (576 bytes) : 4003 allocated (2305728 bytes), 4003 used, 0 failures, 1 users, @0x8be140=08 [SHARED]
```
`tune.vars.txn-max-size 1048576` was tried, but no help to this issue. Thereby I suspect that all answers have not been freed since start-up.

**Comment by chipitsine** [comment]
@pyhd , can you provide `mydns` resolver section ? also, I could not find any leak in similar config. can you try valgrind ?

**Comment by pyhd** [comment]
```
resolvers mydns
        nameserver dns1 1.1.1.1:53
        nameserver dns2 8.8.8.8:53
        nameserver dns3 208.67.222.222:53
        nameserver dns4 9.9.9.9:53
        resolve_retries 3
        timeout resolve 1s
        timeout retry   1s
        hold nx         300s
        hold valid      900s
```
Also I forgot to mention this:
```
    stick-table type binary len 32 size 100k expire 2h
    tcp-request content track-sc1 payload_lv(43,1) if { req.ssl_sni,lower -m found }
```

This issue was found in product environment (10 servers), so I am afraid I cannot offer the valgrind details.

**Comment by pyhd** [comment]
@chipitsine  I just wonder why thousands of "allocated" are always "used" after days.

**Comment by wtarreau** [comment]
I looked at the DNS code and I don't understand when these "answer items"
are supposed to be freed. I only see them freed on error paths and when
they are checked for expiration in dns_check_dns_response(), so I could
be wrong, but I suspect that if a response is used only once and not
looked up again, it will never be released. While it should not happen
with servers, it could possibly be the case with "do-resolve" if used
with varying arguments. Again I could be wrong, I don't know well how
this works.

**Comment by bedis** [comment]
Hi there,

Thanks for reporting, I'll have a look and see what I can do to fix this!

**Comment by bedis** [comment]
The output from @pyhd shows a high number in the response records pool. They are associated to a "dns_response" which itself is linked to a "dns_resolution".
So we should `pool_free()` those records either when we free / clean a dns_response or a dns_resolution (functio `dns_free_resolution()` ).

I'll propose a patch soon to fix this.

**Comment by bedis** [comment]
@pyhd so, I have a fix, but I found an other bug while testing it (https://github.com/haproxy/haproxy/issues/236).
I thought I fixed the leak but it seems I can still see the pool size increasing over time :/ so I am going to double check what's happening.

**Comment by bedis** [comment]
Actually, dns it's not thread safe.
My current patch works perfectly with nbthread 1 only, so we need to fix issue above before moving forward here

**Comment by wtarreau** [comment]
@bedis What's the status of this bug ? Did you try your patch again ? Some issues were addressed since it was reported.

**Comment by pyhd** [comment]
As I tried on a dual-core system, with additional options "nbproc 1" and "nbthread 1", 2.0.11 haproxy almost crashed everyday.

> Dec 22 09:13:13 haproxy[9993]: [ALERT] 355/091313 (9996) : A bogus STREAM [0x2a1b9d0] is spinning at 261681 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x2a1b9d0 src=10.0.67.231 fe=tcpin be=tcpin dst=unknown rqf=80000 rqa=22 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x2b08c00,200 ab=(nil),0 csb=(nil),0 cof=0x27ead00,80203306:PASS(0x2510210)/RAW((nil))/tcpv4(66) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]

> Dec 22 09:13:13 haproxy[9996]: A bogus STREAM [0x2a1b9d0] is spinning at 261681 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x2a1b9d0 src=10.0.67.231 fe=tcpin be=tcpin dst=unknown rqf=80000 rqa=22 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x2b08c00,200 ab=(nil),0 csb=(nil),0 cof=0x27ead00,80203306:PASS(0x2510210)/RAW((nil))/tcpv4(66) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]

> Dec 22 09:13:13 haproxy[9993]: [ALERT] 355/091313 (9993) : Current worker #1 (9996) exited with code 134 (Aborted)

**Comment by pyhd** [comment]
2.0.8 crashed either.
But on my 1 core system with 2.0.3, this feature works fine.

**Comment by lukastribus** [comment]
There are some DNS fixes in `2.0.12`, although they are related to threading, so I'm not sure if they would fix an issue that also happens with `nbthread 1`, but it's worth a try.

**Comment by capflam** [comment]
Fixed now.

**Comment by pyhd** [comment]
Though this issue has been fixed, now it crashes in hours.

> A bogus STREAM [0x193c670] is spinning at 100000 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x193c670 src=172.16.176.152 fe=tcpin be=tcpin dst=unknown rqf=80000 rqa=22 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x193c620,8200 ab=(nil),0 csb=(nil),0 cof=0x193c2e0,80003300:PASS(0x193c5a0)/RAW((nil))/tcpv4(19) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) filters={}]

**Comment by capflam** [comment]
Hum... not good. Ok, I'll try to understand how all this part really works...

**Comment by capflam** [comment]
@pyhd I pushed a fix for you spinning stream. The fix has been backported as far as 2.0. Could you test it again please ?

**Comment by Cherish98** [comment]
> @pyhd I pushed a fix for you spinning stream. The fix has been backported as far as 2.0. Could you test it again please ?

@capflam Thanks for the fix. Before 2.2.2, haproxy always crashes (spinning stream) when performing "do-resolve" on a nonexistent domain. I can't speak for @pyhd, but it worked for me.

**Comment by capflam** [comment]
Thanks. The fix is indeed part of the 2.2.2. So on the 2.2.1, the bug is still present. It is also fixed in the 2.1.8 and 2.0.17.

**Comment by TimWolla** [comment]
@capflam Should this be relabeled to 'status: fixed' again?

**Comment by capflam** [comment]
Oh yes, of course. Thanks

**Comment by pyhd** [comment]
@capflam Thanks for your jobs. It has been verified on various servers for a week.
