### ISSUE TITLE
When a time jump occurs during HAProxy operation, accessing via curl  results in an error: 'connection reset by peer.'

### ISSUE THREAD

**Issue by swimlessbird** [haproxy/haproxy#2704]
### Detailed Description of the Problem

When the configuration tcp-request connection reject if { fe_sess_rate gt 100 } is set, and a time jump occurs during HAProxy operation, HAProxy incorrectly records the session rate (SessRate). This results in all new connections being reset and closed.
#### haproxy
```
# echo show info | socat stdio /var/lib/haproxy/haproxy.sock | grep SessRate

SessRate: 331879881
SessRateLimit: 0
MaxSessRate: 228
```
#### Frontend
```
# curl -k https://xx.xx.xx.xx
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to xx.xx.xx.xx:443
```

### Expected Behavior

Curl can successfully communicate.

### Steps to Reproduce the Behavior

1. Start haproxy  have configuration "tcp-request connection reject if { fe_sess_rate gt 100 }".
2. In Frontend,use wrk make  fe_sess_rate gt 100 .
3. In HAproxy,use `date -s 60day;sleep 1;date -s -60day` make  time jump
4. In Frontend,use curl to curl vip

### What is your configuration?

```haproxy
global
    stats socket /var/lib/haproxy/haproxy.sock mode 600 level admin
    daemon
    maxconn 64000
    spread-checks 4
    log /dev/log local5 debug
    nbthread 4

defaults
    log      global
    option   dontlognull
    option   tcplog
    retries  3
    timeout  connect 300s
    timeout  client  300s
    timeout  server  300s
    option   redispatch
    balance  roundrobin

listen vip_v4
    bind xx.xx.xx.xx:443
    mode tcp
    maxconn 15000
    balance roundrobin

    tcp-request inspect-delay 100ms
    tcp-request connection reject if { fe_sess_rate gt 100 }
    timeout client 1500s
    timeout server 1500s
    server rs1 xx.xx.xx.xx:443 check inter 2000 rise 3 fall 3 weight 1

listen vip_v6
    bind xx::xx:443
    mode tcp
    maxconn 15000
    balance roundrobin

    tcp-request inspect-delay 100ms
    tcp-request connection reject if { fe_sess_rate gt 100 }
    timeout client 1500s
    timeout server 1500s
    server rs1 xx::xx:443 check inter 2000 rise 3 fall 3 weight 1
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.4-7a59afa 2024/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.4.html
Running on: Linux 5.10.0-182.0.0.95.h2166.eulerosv2r13.aarch64 #1 SMP Tue Sep 3 04:12:25 UTC 2024 aarch64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv -DMAX_SESS_STKCTR=12
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE2=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 1.1.1wa  16 Nov 2023
Running on OpenSSL version : OpenSSL 1.1.1wa  16 Nov 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.1

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by xanoxes** [comment]
We reproduce this problem and found that the curr_tick in freq_ctr_total is 1271499440, but the global_now_ms in freq_ctr_total  is  3857555132, thus remain has an underflow to 1708912604.

**Comment by wtarreau** [comment]
Thanks for this report! That's extremely surprising because we've been taking great care of time jumps for more than a decade now, but based on your details it looks like it's got broken somewhere! Normally jumps backwards are compensated for, and jumps forwards are tied to the max poll delay. This was made necessary ~15 years ago due to ugly VMs and the first multi-core CPUs with desynchronized clocks. I'm going to have a look now.

**Comment by xanoxes** [comment]
We made a change :
```
--- a/src/freq_ctr.c
+++ b/src/freq_ctr.c
@@ -29,6 +29,7 @@ ullong freq_ctr_total(const struct freq_ctr *ctr, uint period, int pend)
 {
        ullong curr, past;
        uint curr_tick;
+       uint toofar = 0;
        int remain;

        for (;; __ha_cpu_relax()) {
@@ -56,13 +57,20 @@ ullong freq_ctr_total(const struct freq_ctr *ctr, uint period, int pend)
                break;
        };

+       if (((curr_tick + period) < global_now_ms) || ((global_now_ms + period) < curr_tick))
+               toofar = 1;
+
        remain = curr_tick + period - global_now_ms;
-       if (unlikely(remain < 0)) {
+       if (unlikely(remain < 0 || toofar)) {
                /* We're past the first period, check if we can still report a
                 * part of last period or if we're too far away.
                 */
+
+               if (((curr_tick + 2*period) < global_now_ms) || ((global_now_ms + 2*period) < curr_tick))
+                       toofar = 2;
+
                remain += period;
-               past = (remain >= 0) ? curr : 0;
+               past = (toofar != 2) ? curr : 0;
                curr = 0;
        }
```

**Comment by wtarreau** [comment]
Thanks for the info, I'll look at this first. Maybe it's only the freq_ctr handling that's wrong.
Please be careful regarding your patch, as the time wraps every 49.7 days, and does it first within 20s of the boot (purposely to catch rare time wrapping bugs). There are tick_* functions that handle the wrapping of time and that will be more reliable. Above you could end up by accident setting the "toofar" for too long every 24.8 days for example. I preferred to warn you, but I'm looking at this right now.

**Comment by wtarreau** [comment]
I'm seeing what's happening (difficult to perfectly grab at first). We have a correction against local time deviation and another one to consider the global time so that no thread has an older time than the currently effective one. The two-step checks result in the local offset not being updated upon the first detection since the local time is still within expectations regarding the global offset, and upon the second poll, the drift does not exist anymore so we restart applying the offset and propagating it to the global time, which suddenly jumps into the future and stays there since it is monotonic. And from there the time doesn't move anymore.

Hmmm... Head scratching session ahead. I think I need to interleave these two checks a bit more so that the offset is recalculated from the global time upon change, no longer the local one. I think it's broken since 2.7 or 2.8...

**Comment by xanoxes** [comment]
Yep, now it only refresh the curr_tick in update_freq_ctr_period in the conn_complete_session. Since the tcp_exec_l4_rules failed it will never be refreshed. Considering that there may be some other check, we now just fix the freq_ctr_total so that most of rules like the session_rate can be fixed.

**Comment by wtarreau** [comment]
OK finally it could be fixed way more easily than I feared. The problem was introduced in 2.7 when avoiding to always update the date offset since it's super expensive on large systems. But remains very cheap to update every time we observe a time jump and that's what is mandatory. I did that in this commit and it now works reliably like before now: e8b1ad4c2b3, and also backported it to 3.0-maint (commit 61d73137f19), so that a git pull will deliver you all latest fixes. It should apply well to any recent version anyway.

Thanks a lot for your detailed info, these were really useful. I'm horrified that it remained unnoticed for 2 years! In one way, it means that systems now provide more reliable clocks than they used to.

**Comment by firexinghe** [comment]
This problem also exist in the latest version of  2.4.x.

**Comment by wtarreau** [comment]
Hmm strange but I'll check, thanks for the info.

**Comment by wtarreau** [comment]
@firexinghe I checked on 2.4.27 and both its clock and the fe_sess_rate are super stable for me while changing the date. How does the problem manifest itself for you ? Could you please share logs, configs, exact version output ?

**Comment by xanoxes** [comment]
We prodecu by this way:
1、run this cmd in client：wrk -c 2000 -d 1000 https://[ip]:port &
2、run this shell bash in server：
i=${1:-1}

while :
do
        date -s '-30day'
        sleep $i
        date -s '30day'
        sleep $i
        date -s '-1hour'
        sleep $i
        date -s '1hour'
        sleep $i
        date -s '-1min'
        sleep $i
        date -s '1min'
        sleep $i
        date -s '-1second'
        sleep $i
        date -s '1second'
        sleep $i
done
3、run this cmd in server：
watch -d -n1 'echo "show info" | socat stdio /var/lib/haproxy/haproxy.sock|grep -i rate'

**Comment by firexinghe** [comment]
Use the same method to reproduce the problem. The e8b1ad4 patch is added.  This problem can be reproduced in 2.9.5. It does not fix the problem.

**Comment by wtarreau** [comment]
I'm not having the problem with your repro above. There are definitely variations which are unavoidable since there are time jumps which need to be detected and corrected. After correction, the variations can remain around +/-100ms, which definitely results in some metrics to be off for one measure. Here for example, injecting at 2000 conn/s I'm seeing 2000/s session rate all the time except at the precise moment of *some* date changes, where it can be at 1900 or 1700. I've even seen 52 once. But there are no stuck counters anymore and the operations continue normally. And let's keep in mind that we're not speaking about an admin manually fixing the date of the server here, but about an attack consisting in changing the time back and forth each and every second. So I consider that this works as designed now.

**Comment by wtarreau** [comment]
This was backported as far as 2.8, I'm closing now!

**Comment by firexinghe** [comment]
No, change the time repeatedly to trigger the problem. The problem arises by chance. 
The time changes repeatedly, which may trigger problems. 
There is a high probability that the problem is triggered by the 2.4 branch. 
The problem can also be reproduced in the 2.6 branch.

Because the stable trigger point of the problem is uncertain, the problem is triggered in this way.

**Comment by firexinghe** [comment]
Because I do not know the software package, I do not know the scenarios that trigger the "connection reset by peer." message.

This application scenario is found through the code, which is in line with the current situation. It's just that the probability of triggering is not high.

Hope to get your help.@wtarreau

**Comment by wtarreau** [comment]
That's exactly what I did, I used the proposed script above that changes the time every second. Just a question, were you running wrk on the same machine ? I'm asking because if that was the case, then it was also affected by the time changes, which can cause a boost of connection rate.

But now on all versions I'm seeing the correct behavior: the reported rate is close to reality during time jumps: if the time jumps backwards, it is not changed and only the offset is updated so that in the worst case the measurement period is extended by the effective sleep time of the poll() call (i.e. delay between two events, in the order of microseconds to a few milliseconds depending on the load). And if the time jumps forward, it is bound to the sleep time in case of poll() timeout, or returns the current time if interrupted,

With that said I'm continuing testing on different architectures and with different test scenarios just in case I spot another anomaly.

**Comment by wtarreau** [comment]
Note, I'm suspecting there might be a corner case if the date jumps backwards **before** retrieving `before_poll`. It's difficult to see the effects, but that might be an explanation why you'd still be seeing some strange cases (though an exact description of how you reproduce it would definitely help).

**Comment by wtarreau** [comment]
I think that's it. If the time jumps before calculating before_poll, and the wakeup is within expectations (date vs before_poll), then we don't need to correct it and we apply the old offset to the new date because we couldn't detect the jump. Thus I think we also need to detect that one by checking the date against after_poll as well (which is obviously less precise since it has experienced a round of tasks, but it still sets boundaries).

**Comment by wtarreau** [comment]
Tests indicate that it's more complicated than I thought but I have sufficient notes about various corner cases to take into account. I'd also like to automatically switch to clock_gettime(CLOCK_MONOTIME) when it's available (now we know it) and only fall back to the current portable method when not available, but it's tricky when using busy polling as it's not updated there and on some platforms it's super expensive (particularly some VMs).

**Comment by wtarreau** [comment]
OK with that it now works fine. In addition for 3.1 I'm adding changes to switch to the system's monotonic clock when we see that it's ticking. We were already using it for profiling (thus totally opportunistically), but the code is flexible enough that we can now use it when it's ticking and fall back to the current corrected clock when it's not ticking. That should provide the best of both solutions, portability and increased stability.

For now you can try the attached patch, it detects the occasional time jumps that happen while the thread is working, and sets a limit to them (no backwards jumps, max 2s forward).
[0001-BUG-MEDIUM-clock-detect-and-cover-jumps-during-execu.patch.txt](https://github.com/user-attachments/files/16923366/0001-BUG-MEDIUM-clock-detect-and-cover-jumps-during-execu.patch.txt)

**Comment by firexinghe** [comment]
The historical introduction time of the problem was found. The problem was introduced starting from version 2.4.0-dev17, as follows:
44982715b --> causes curl stuck
4d01f3dcd --> fixed curl stuck, but the introduced rate value remained unchanged
fe16126ac --> fixes the problem of unchanged rate value and introduces the problem of extremely large rate value

I tested 0001-BUG-MEDIUM-clock-detect-and-cover-jumps-during-execu.patch.txt using the 2.6 branch. 
It can still be reproduced, but the probability of triggering the problem is very low.

**Comment by wtarreau** [comment]
OK thanks for the tests. On my side I couldn't reproduce the freezes anymore, but now I see from the code how this could happen: if a thread observes a backwards jump and updates the offset accordingly, then the time is fixed again instantly (observed when systemd-timesyncd is running), and another thread gets the correct date again, it may apply the increased offset. Normally this is constrained by the 2 seconds boundary that's enforced on before_poll, so the issue should not last more than 2 seconds if it ever happens. But if it's only caused by now_offset, maybe the attached patch improves the situation.
[0001-EXP-clock-validate-that-now_ns-still-applies-to-the-.patch.txt](https://github.com/user-attachments/files/16930045/0001-EXP-clock-validate-that-now_ns-still-applies-to-the-.patch.txt)

**Comment by xanoxes** [comment]
Unfortunately, we found another way to reproduce it. Curl the same ip and port after a month, we can probably trigger the bug without time jump.

**Comment by wtarreau** [comment]
Note that time ranges of a month are not supported, as the time wraps every 49.7 days, everything that's 24.8 days before now is in the past, everything that's 24.8 days after is in the future. So if you're updating your counters after more than 24.8 days you're refreshing dates of the past.

**Comment by xanoxes** [comment]
NOW we meet a problem that if we curl after 24.8 days, the tcp_exec_l4_rules() will fail and the curr_tick will never be refreshed in conn_complete_session(). Thus it will always fail with same ip and port.

**Comment by wtarreau** [comment]
Please could you make a complete report ? What you describe is obviously totally unrelated with the config above, which doens't have any such large expiration delays. I still have no idea what you're testing nor how, and it's even harder to infer anything without a matching configuration. All I'm reading for now is "the problem continues" but the description of the problem as I read it is that on the opposite, it works as expected. I don't even know if you're related with the original reporter or if it's independent, but please provide a description of your problem with config, observations, expectations etc. As usual.

**Comment by wtarreau** [comment]
BTW, I've merged into 3.1 some changes to default to CLOCK_MONOTONIC when available, since we were already using it opportunitistically. This way the current method of detecting and correcting time jumps will only be for legacy systems not supporting it.

**Comment by wtarreau** [comment]
I'm marking fixed, and closing since all possible fixes were backported to 2.8.
