### ISSUE TITLE
Add new backend via Runtime API

### ISSUE THREAD

**Issue by lizj3624** [haproxy/haproxy#3094]
### Your Feature Request

Adding new backends also frequently requires configuration changes. We hope to support the addition of new backends via runtime APIs to avoid frequent reloads.

### What are you trying to do?

Add new backend via Runtime API

### Output of `haproxy -vv`

```plain
haprxoy 3.2.x
```

**Comment by wtarreau** [comment]
It's already planned and we have ideas about how to do it, based on the experience gathered on the same feature for the servers. It will take quite a lot of time however because a lot of things internally (including sizing that guarantees the stability) are based on the knowledge of the backends. But we're still positive about it.

**Comment by lizj3624** [comment]
@wtarreau very good!  I work at an e-commerce company, handling load balance and DNS. Our load balancing cluster is built with HAProxy, with 20 HAProxy nodes in each cluster. Each node handles thousands of domain configurations, and the configuration is the same across all nodes in a cluster. Every time we add a new domain, we need to reload the configuration. However, with 30,000 TCP connections per node, this reload impacts service availability. Currently, we solve this by using dynamic solutions with ACLs and use_backend through maps. Therefore, we are hoping to add support for dynamically updating backends.

haproxy config:
```conf
frontend
   bind 1.1.1.1:80 # 1.1.1.1 is vip

   acl a hdr(host) -i a.cc.com
   use_backend a_backend if a

   acl b hdr(host) -i b.cc.com
   use_backend b_backend if b

backend a_backend
    server srv1 192.0.2.1:80

backend b_backend
    server srv1 192.0.2.1:80
```

Currently, we are using HAProxy version 1.5.12. Reloading every time we make a change no longer meets our needs, so we are considering an upgrade. One option is to upgrade to HAProxy 3.2 and use dataplaneapi, which has a low upgrade cost, but we would still need to reload when adding new backends. The other option is to switch to Envoy, which supports dynamic configuration and requires almost no reloads, but the upgrade cost is higher.

**Comment by wtarreau** [comment]
A lot of users heavily rely on maps to perform dynamic configurations. But I agree that it has limits.

In the model we've thought about, we'll have to request the creation of a backend from the CLI, by either duplicating another existing backend, or relying on a named "defaults" section (we've already implemented "backend foo from bar" for this reason). The ability to change the backend's config from the default will be very limited but on the other hand, those who need to create backends on the fly generally rely on a few templates that correspond to application types (which will then be in defaults). Even rules are supported in defaults sections nowadays, so it seems to make quite some sense to just create a backend then fill it with servers. We're interested in hearing about your feeling about this by the way.

In any case, if you're currently on 1.5.12, the gap will be huge! You'll discover the addition of DNS resolution and the ability to add servers from the CLI without reloading. This was the most commonly requested feature, as backends are generally added less often than servers.

**Comment by lizj3624** [comment]
I agree that the maps feature has certain limitations. It doesn't solve the problem of supporting multiple domains, as well as URL and path routing, under the same frontend.

I haven't tested the functionality of copying from an existing backend or defaults configuration to create a new backend yet, but I'll check it first. Since the timeout and load balancing algorithms can differ between backends, adding a separate, independent backend seems like a more flexible solution.

We’ve customized HAProxy version 1.5.12 to support dynamic additions of frontend, ACLs, use_backend, backend, server configurations, and more. However, this customization requires significant changes to the HAProxy architecture, making it difficult to merge into newer versions of HAProxy.

For backends with fewer servers, DNS dynamic resolution can work to handle server changes. But for backends with many servers—some having over 100, or even over 1,000 servers—DNS resolution may not be the best approach.

**Comment by wtarreau** [comment]
Yeah, DNS is a poor choice to populate farms. We've done it, I won't say I regret it because by then there was no other solution, but it has done more harm than good. However, being able to rely on the DNS in dynamic environments is convenient because IPs can change between reboots for example. Being able to change timeouts at runtime definitely is among the things we want to support, it's not very hard (actually it's even supported on a per-request basis using rules nowadays). And the CLI's "add server" and "del server" command will surely be of interest to you based on your description.

**Comment by lizj3624** [comment]
"In the model we've thought about, we'll have to request the creation of a backend from the CLI, by either duplicating another existing backend, or relying on a named "defaults" section (we've already implemented "backend foo from bar" for this reason)."  Is it expected that HAProxy version 3.3.x will support this feature?

**Comment by wtarreau** [comment]
Unfortunately no. We initially thought there would be a tiny possibility but now it's certain this will not be for 3.3. I guess 3.5 is more likely, though 3.4 doesn't yet seem impossible.

**Comment by antcs** [comment]
@wtarreau Do you already have a rough plan by when 3.5 might be available?

**Comment by wtarreau** [comment]
roughly 1 year after 3.3 which is going to be emitted today if everything's OK.
