### ISSUE TITLE
dynamically set ssl cert does not configure the ciphers correctly

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#429]
steps to reproduce

0. build haproxy using openssl-1.0.2

1. create config using `reg-tests/ssl/set_ssl_cert.vtc` primitives

```
global

        maxconn 4096
        user root
        group root
        daemon
        log 127.0.0.1 local0 debug
        stats socket "/tmp/stats" level admin

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option  redispatch
        option  http-server-close
        option  forwardfor
        timeout connect 5000
        timeout client  50000
        timeout server  50000


frontend ft_test
    mode    http
    bind    :443 ssl crt /root/haproxy/reg-tests/ssl/common.pem alpn h2,http/1.1
    bind    :80
    redirect scheme https code 301 if !{ ssl_fc }
        option forwardfor
        option http-server-close
        default_backend nextcloud

backend nextcloud
        option httpclose
        option forwardfor
        server node1 127.0.0.1:8080
```

start haproxy, run `nmap -sV --script ssl-enum-ciphers -p 443 127.0.0.1`

```
PORT    STATE SERVICE    VERSION
443/tcp open  ssl/https?
| ssl-enum-ciphers: 
|   SSLv3: No supported ciphers found
|   TLSv1.0: 
|     ciphers: 
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_SEED_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_IDEA_CBC_SHA - weak
|       TLS_RSA_WITH_RC4_128_MD5 - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_SEED_CBC_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.1: 
|     ciphers: 
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_SEED_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_IDEA_CBC_SHA - weak
|       TLS_RSA_WITH_RC4_128_MD5 - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_SEED_CBC_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.2: 
|     ciphers: 
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_DHE_RSA_WITH_SEED_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_IDEA_CBC_SHA - weak
|       TLS_RSA_WITH_RC4_128_MD5 - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_SEED_CBC_SHA - strong
|     compressors: 
|       NULL
|_  least strength: weak

```

curl also works

```
# curl --insecure https://127.0.0.1
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
# 

```

now let us apply dynamic change

```
   echo -e "set ssl cert /root/haproxy/reg-tests/ssl/common.pem <<\n$(cat /root/haproxy/reg-tests/ssl/ecdsa.pem)\n" | socat "/tmp/stats" -
   echo "commit ssl cert /root/haproxy/reg-tests/ssl/common.pem" | socat "/tmp/stats" -
```

nmap output

```
PORT    STATE SERVICE    VERSION
443/tcp open  ssl/https?
| ssl-enum-ciphers: 
|   SSLv3: No supported ciphers found
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_ECDH_ECDSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|_  least strength: strong

```

curl

```
# curl --insecure https://127.0.0.1
curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).
# 
```

haproxy reports

```
fd[000d] OpenSSL error[0x1408a0c1] ssl3_get_client_hello: no shared cipher
```

that's not true actually, according to nmap output and tcpdump we can see a lot of ciphers suites supported by both client and server

[443.zip](https://github.com/haproxy/haproxy/files/4007878/443.zip)

**Comment by chipitsine** [comment]
seems, that `SSL_CTX_set1_curves_list` is mandatory for openssl-1.0.2 (it is not called when certificate is changed RSA --> EC)

**Comment by wlallemand** [comment]
That's weird, SSL_CTX_set1_curves_list() is supposed to be called during the initilisation of a ckch instance, which is done during the startup of haproxy and also during the commit of the certificate. I'll do some tests but it's possible that it is not related at all with "set ssl cert".

**Comment by wlallemand** [comment]
@chipitsine Are you sure your version of curl is supporting ECDSA because in my opinion the ciphers are good.

**Comment by chipitsine** [comment]
I created dedicated VM for testing. curl shows EC suited in SSL CLient Hello message, have a look at attached 443.pcap file.

I'm sure it is something related to ec initialization, which is slightly different for openssl-1.0.2, i.e. all things were initialized for RSA cert, after new cert is applied, not all required initialization steps were taken (I guess openssl-1.1.X configures those steps automatically)


I planned to have deeper look once I will found a time

**Comment by wlallemand** [comment]
Could you try to add "--no-sessionid" on the curl lines? It could be a bug related to the reuse of the session in curl.

**Comment by chipitsine** [comment]
As you can see in 443.pcap, no session is involved. It was very first curl run after VM start


But, just in case I will double check later today

**Comment by chipitsine** [comment]
attaching a picture for a while. will have a look at ec initialization machinery later

![Screenshot from 2020-01-06 16-35-12](https://user-images.githubusercontent.com/2217296/71816061-3da13900-30a3-11ea-8ea5-1fbecfd5321e.png)

**Comment by ehocdet** [comment]
this patch should fix the issue:
```
diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index 67c3915ac..baccba988 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -5209,7 +5209,7 @@ int ssl_sock_prepare_ctx(struct bind_conf *bind_conf, struct ssl_bind_conf *ssl_
        if (!conf_curves) {
                int i;
                EC_KEY  *ecdh;
-#if (HA_OPENSSL_VERSION_NUMBER >= 0x10101000L)
+#if ((HA_OPENSSL_VERSION_NUMBER >= 0x1000200fL) || defined(LIBRESSL_VERSION_NUMBER))
                const char *ecdhe = (ssl_conf && ssl_conf->ecdhe) ? ssl_conf->ecdhe :
                        (bind_conf->ssl_conf.ecdhe ? bind_conf->ssl_conf.ecdhe :
                         NULL);

```

**Comment by chipitsine** [comment]
I will test soon.

Hoever, why do we need to ifdef for LIBRESSL here ? reg-tests (including dynamically changed cert) do not fail for libressl, I tested that.

**Comment by ehocdet** [comment]
This patch is not related to dynamically changed cert.
Patch is to force SSL_CTX_set_ecdh_auto for openssl-1.0.2,  it is set per default for newer versions, perhaps is also the case for LIBRESSL.
(curves  should  replace ecdhe  param since openssl-1.0.2 https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_ecdh_auto.html)

**Comment by chipitsine** [comment]
without that patch things are definetly wrong for openssl-1.0.2, but nothing seems to be wrong for libressl.

**Comment by chipitsine** [comment]
@ehocdet , I tried on my VM, no luck, so have a look

https://travis-ci.com/chipitsine/haproxy/builds/143279686

1. your patch seem to be for some other commit, it does not apply for current master (but I applied manually)

2. I did not add libressl ifdef, however libressl passes tests (except another failing test)

3. openssl-1.0.2 still does not work
(we can see `***  h1   debug|fd[000e] OpenSSL error[0x1408a0c1] ssl3_get_client_hello: no shared cipher` in debug logs)

thank you for your efforts!

**Comment by ehocdet** [comment]
Ok, openssl-1.0.2 is the only one who need SSL_CTX_set_ecdh_auto and i gess call SSL_CTX_set1_curves_list explicitly.
Can you test this?:
```
diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index 67c3915ac..16d091a83 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -5195,7 +5195,8 @@ int ssl_sock_prepare_ctx(struct bind_conf *bind_conf, struct ssl_bind_conf *ssl_
                SSL_CTX_set_alpn_select_cb(ctx, ssl_sock_advertise_alpn_protos, ssl_conf_cur);
 #endif
 #if ((HA_OPENSSL_VERSION_NUMBER >= 0x1000200fL) || defined(LIBRESSL_VERSION_NUMBER))
-       conf_curves = (ssl_conf && ssl_conf->curves) ? ssl_conf->curves : bind_conf->ssl_conf.curves;
+       conf_curves = (ssl_conf && ssl_conf->curves) ? ssl_conf->curves :
+               (bind_conf->ssl_conf.curves ? bind_conf->ssl_conf.curves : "P-256:P-384");
        if (conf_curves) {
                if (!SSL_CTX_set1_curves_list(ctx, conf_curves)) {
                        memprintf(err, "%sProxy '%s': unable to set SSL curves list to '%s' for bind '%s' at [%s:%d].\n",

```

**Comment by chipitsine** [comment]
still `***  h1   debug|fd[000e] OpenSSL error[0x1408a0c1] ssl3_get_client_hello: no shared cipher`

https://travis-ci.com/chipitsine/haproxy/jobs/273075439

**Comment by ehocdet** [comment]
Bad. My patch should, at least, changed the nmap outputs.
I arrive at the end of what I had noticed on the problematic ecdhe vs curves parameter for quick fix proposal. This should be fixed for openssl-1.0.2 because it used old SSL_CTX_set_tmp_ecdh if no curves is set (the most recent Libssl implement SSL_CTX_set_tmp_ecdh with SSL_CTX_set1_curves). But is not the main issue for this case.

**Comment by wlallemand** [comment]
Looks like there is no problem when starting with an ECDSA certificate, so it's really related to the 'set ssl cert' feature. Something should be missing on this code path, I'm investigating.

**Comment by chipitsine** [comment]
nmap output was good already, so I did not run nmap again. I'll try tomorrow

**Comment by wlallemand** [comment]
My tests showed that:

- Replacing a RSA certificate by an RSA one still works
- Adding an ECDSA bind in parallel does not change anything
- Starting with an ECDSA certificate works, but once it is replaced by another EDSA one it does not works anymore, so it's not related to the change from RSA to ECDSA.
- The ciphers are indeed OK

It probably lacks something related to the ECDSA which is initialized during the configuration parsing but not during the 'commit ssl cert'. However the certificate change pass through the ssl_sock_prepare_ctx() so it might be something initialized elsewhere.

**Comment by chipitsine** [comment]
it is true that ss_sock_prepare_ctx() is called.

however (I added debug to various point of it), for example  https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L5175-L5182 is not called upon certificate change. That makes me beleive that `conf_curves` is false for some reason. I did not yet investigated deeper.

so, some parts are called, some not.

**Comment by chipitsine** [comment]
I think I can add debug info to ssl_sock_prepare_ctx() and compare how it is called during initial certificate set and during certificate change.

**Comment by wlallemand** [comment]
> however (I added debug to various point of it), for example https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L5175-L5182 is not called upon certificate change. That makes me beleive that `conf_curves` is false for some reason. I did not yet investigated deeper.

That's expected, conf_curves is the configuration of the curves, and there is not curves configuration in the config file, and ssl_conf does not exist since it's not a crt-list, it's not called either during a start with an ecdsa file without curves configuration.

**Comment by chipitsine** [comment]
Well, I added debug to ssl_sock_prepare_ctx()

the following part is called on initial certificate set, and not called on update:

https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L5087-L5131

seems, something really happens outside ssl_sock_prepare_ctx()

**Comment by wtarreau** [comment]
Interesting, this part is used only to initialize the default dh-param
if it was not set in the conf. But maybe the one we initialize becomes
incompatible with future certificates. That could explain why doing it
after creating initial certs doesn't prevent them from working but
prevents new ones from working for example.

A good test would consist in setting dh-param in the configuration to
see if it changes anything. In this case this code will not be called.
However maybe some other parts depending on this are also initialized
and can make a difference, so that would possibly only provide a hint
about a possible cause.

**Comment by chipitsine** [comment]
yeah, `setting dh-param in the configuration` is good thing to play with

**Comment by chipitsine** [comment]
funny thing, occasionely I've found another strange 


./haproxy -vv

```
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
```

haproxy -d -f /etc/haproxy/haproxy.cfg

```
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED

```

same is reproduced on current master (no debug patches applied), OS = CentOS 7.7.1908



what's wrong with `select` ?

**Comment by chipitsine** [comment]
well, adding

```
	ssl-dh-param-file /etc/haproxy/dhparam.pem
	tune.ssl.default-dh-param 2048
```

did change how ssl_sock_prepare_ctx() is called.
however, from curl point of view nothing changed, it works when cert is set initially, and it does not work when cert is dynamically updated

**Comment by chipitsine** [comment]
indeed, after adding `noepoll`, `nopoll`

```
Available polling systems :
     select : pref=150,  test result FAILED
       poll : disabled,  test result OK
      epoll : disabled,  test result OK
Total: 3 (0 usable), will use poll.

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
[ALERT] 010/183238 (1577) : No polling mechanism available.
  It is likely that haproxy was built with TARGET=generic and that FD_SETSIZE
  is too low on this platform to support maxconn and the number of listeners
  and servers. You should rebuild haproxy specifying your system using TARGET=
  in order to support other polling systems (poll, epoll, kqueue) or reduce the
  global maxconn setting to accommodate the system's limitation. For reference,
  FD_SETSIZE=1024 on this system, global.maxconn=4096 resulting in a maximum of
  8221 file descriptors. You should thus reduce global.maxconn by 3599. Also,
  check build settings using 'haproxy -vv'.

```

**Comment by chipitsine** [comment]
also, ssl_sock_prepare_ctx() is called two times during initial setup, and only one time during dynamic cert update

**Comment by chipitsine** [comment]
openssl-1.1.0i - works well
openssl-1.1.0h - does not work

this could help us to fix issue

**Comment by chipitsine** [comment]
I've found particular commit between 1.1.0h and 1.1.0i

https://github.com/openssl/openssl/commit/e9d26dc85238c071117d911704f5f769e79b46a1

@ehocdet , @wlallemand , @wtarreau ?

**Comment by wlallemand** [comment]
Thanks for you work, Ilya, it will be helpful. I'm still convinced that something is not correctly initialized in the "set ssl cert" codepath, I'll look into this during the week.

**Comment by chipitsine** [comment]
what is strange, is the fact that openssl actually accepts certificate and does not return any error.

ok, we did mess on curves (server curves do not match certificate curves), so, why not to reject cert ?

**Comment by wlallemand** [comment]
I spend some time on this today, and it was a problem in HAProxy since the certificate were working on startup.
In fact it's a very stupid one, unrelated to ECDSA. The wrong SSL_CTX were initialized during the certificate change. So it affects every version of OpenSSL. I think I can be ashamed of this one :-)

**Comment by wlallemand** [comment]
Backported in 2.1.

**Comment by wtarreau** [comment]
Kudos for finally nailing it down! You have no reason for being ashamed, only those who do nothing do not create bugs. Bugs are part of development, what matters is to figure how to reduce the probability of facing the same again in the future. On this one I think that more explicit variables names like "old_inst" instead of "ckchi" would have made it less likely to appear or easier to spot. It's always easy to say afterwards of course :-)
