### ISSUE TITLE
haproxy seamless reload failed.... Is there anyone know what happend? please help

### ISSUE THREAD

**Issue by Kevinz857** [haproxy/haproxy#481]
### haproxy -vv
```
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -m64 -march=x86-64 -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SLZ=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

### Execution
```shell
systemctl reload haproxy
```
 ### the flowing is systemd status of haproxy 
```
haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; enabled; vendor preset: disabled)
   Active: reloading (reload) since Mon 2020-02-03 20:59:23 CST; 23h ago
  Process: 9151 ExecReload=/bin/kill -USR2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 18716 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=0/SUCCESS)
 Main PID: 18722 (haproxy);         : 11272 (haproxy)
   CGroup: /system.slice/haproxy.service
           ├─ 8832 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 8291 -x /run/haproxy/admin.sock
           ├─ 9160 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 8832 -x /run/haproxy/admin.sock
           ├─18722 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 8832 -x /run/haproxy/admin.sock
            └─control
             └─11272 /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -c -q -x /run/haproxy/admin.sock


haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; enabled; vendor preset: disabled)
   Active: avtivating (start-pre) since Mon 2020-02-03 20:59:23 CST; 23h ago
  Process: 9151 ExecReload=/bin/kill -USR2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 18716 ExecReload=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS $RELOADOPTS (code=exited, status=0/SUCCESS)
  Process: 18829 ExecReload=/usr/sbin/haproxy -Ws $CONFIG -p $PIDFILE $EXTRAOPTS (code=exited, status=1/FAILURE)
 Main PID: 18722 (code=exited, status=1/FALIURE);         : 11272 (haproxy)
   CGroup: /system.slice/haproxy.service
            └─control
             └─11272 /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -c -q 
```

### the fllowing is haproxy log
```
Feb 04 20:50:18 haproxy002.test haproxy[2899]: [ALERT] 034/205011 (2899) : Starting frontend profile_49002_frontend: cannot bind socket [0.0.0.0:49002]
Feb 04 20:50:18 haproxy002.test haproxy[2899]: [ALERT] 034/205011 (2899) : Starting frontend profile_49008_frontend: cannot bind socket [0.0.0.0:49008]
Feb 04 20:50:18 haproxy002.test systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
Feb 04 20:50:18 haproxy002.test systemd[1]: Failed to start HAProxy Load Balancer.
Feb 04 20:50:18 haproxy002.test systemd[1]: Unit haproxy.service entered failed state.
Feb 04 20:50:18 haproxy002.test systemd[1]: haproxy.service failed.
Feb 04 20:50:18 haproxy002.test systemd[1]: haproxy.service holdoff time over, scheduling restart.
Feb 04 20:50:18 haproxy002.test systemd[1]: Stopped HAProxy Load Balancer.
Feb 04 20:50:18 haproxy002.test systemd[1]: Starting HAProxy Load Balancer...
Feb 04 20:50:30 haproxy002.test haproxy[2928]: [NOTICE] 034/205024 (2928) : New worker #1 (2950) forked
```

### the fllowing is configuration in haproxy.cfg
```

defaults
  maxconn 300000
  log global
  option redispatch
  option http-server-close
  timeout http-request 10s
  timeout check 10s
  timeout connect 10s
  timeout client 1m
  timeout queue 1m
  timeout server 1m
  timeout http-keep-alive 10s
  retries                 3

global
  daemon
  maxconn 300000
  pidfile /run/haproxy.pid
  stats socket /run/haproxy/admin.sock mode 777 level admin expose-fd listeners
  log 127.0.0.1:514 local2
  chroot      /var/lib/haproxy
  user        root
  group       root
```

the fllowing is content in systemd.service of haproxy
```
[Unit]
StartLimitInterval=0
StartLimitBurst=0
Description=HAProxy Load Balancer
After=network.target

[Service]
EnvironmentFile=-/etc/default/haproxy
EnvironmentFile=-/etc/sysconfig/haproxy
#Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid" "EXTRAOPTS=-S /run/haproxy/admin.sock"
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid"
ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
ExecReload=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS $RELOADOPTS
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
SuccessExitStatus=143
Type=notify

# The following lines leverage SystemD's sandboxing options to provide
# # defense in depth protection at the expense of restricting some flexibility
# # in your setup (e.g. placement of your configuration files) or possibly
# # reduced performance. See systemd.service(5) and systemd.exec(5) for further
# # information.
#
# # NoNewPrivileges=true
# # ProtectHome=true
# # If you want to use 'ProtectSystem=strict' you should whitelist the PIDFILE,
# # any state files and any other files written using 'ReadWritePaths' or
# # 'RuntimeDirectory'.
# # ProtectSystem=true
# # ProtectKernelTunables=true
# # ProtectKernelModules=true
# # ProtectControlGroups=true
# # If your SystemD version supports them, you can add: @reboot, @swap, @sync
# # SystemCallFilter=~@cpu-emulation @keyring @module @obsolete @raw-io
#
[Install]
WantedBy=multi-user.target
```

and I use dataplane api  to update haproy.cfg , seamless reload well at times but very badly at others. Is there anyone knows why?

**Comment by wlallemand** [comment]
Could you upgrade to 2.0.12 ? 2.0.3 is quite old and contains a lot of bugs already fixed in the latest version.

Also it looks like you misconfigured the CLI, your systemd unit file contains 
"EXTRAOPTS=-S /run/haproxy/admin.sock" which is the master CLI (the CLI that allows you to control the master process) and you configured a stats socket in your configuration "stats socket /run/haproxy/admin.sock mode 777 level admin expose-fd listeners" at the same path. It can't work, you need to put 2 differents paths there.

The "stats socket" will be used for the seamless reload, but the master CLI can't be used for it. What is possible is that it tries to retrieve the sockets from the master CLI, and failed. But you should see more errors if that's the case. Also your process shouldn't leave if a reload failed.

Could you try again by fixing this and updating the version? Thanks

**Comment by TimWolla** [comment]
> Also it looks like you misconfigured the CLI, your systemd unit file contains
> "EXTRAOPTS=-S /run/haproxy/admin.sock" which is the master CLI

@wlallemand Note that the line with EXTRAOPTS is commented.

**Comment by wlallemand** [comment]
Oh, you are right, I misread this part. Looks more like a bug than a configuration problem.

**Comment by Kevinz857** [comment]
> Could you upgrade to 2.0.12 ? 2.0.3 is quite old and contains a lot of bugs already fixed in the latest version.
> 
> Also it looks like you misconfigured the CLI, your systemd unit file contains
> "EXTRAOPTS=-S /run/haproxy/admin.sock" which is the master CLI (the CLI that allows you to control the master process) and you configured a stats socket in your configuration "stats socket /run/haproxy/admin.sock mode 777 level admin expose-fd listeners" at the same path. It can't work, you need to put 2 differents paths there.
> 
> The "stats socket" will be used for the seamless reload, but the master CLI can't be used for it. What is possible is that it tries to retrieve the sockets from the master CLI, and failed. But you should see more errors if that's the case. Also your process shouldn't leave if a reload failed.
> 
> Could you try again by fixing this and updating the version? Thanks

thanks ur reply, and I upgrade haproxy version to 2.0.12 .Then I use dataplane api update haproxy.cfg trigger haproxy reload, it's still not work

### the fllowing is haproxy log
```
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend 44609_frontend.
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend recommend_46000_frontend.
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend recommend_46001_frontend.
.....
Feb 04 22:29:42 haproxy001.test haproxy[2201]: [ALERT] 034/222942 (2201) : Failed to get the sockets from the old process!
.....
Feb 04 22:31:09 haproxy001.test systemd[1]: Reload failed for HAProxy Load Balancer.
Feb 04 22:31:09 haproxy001.test systemd[1]: Unit haproxy.service entered failed state.
Feb 04 22:31:09 haproxy001.test systemd[1]: haproxy.service failed.
Feb 04 22:31:09 haproxy001.test systemd[1]: haproxy.service holdoff time over, scheduling restart.
Feb 04 22:31:09 haproxy001.test systemd[1]: Stopped HAProxy Load Balancer.
Feb 04 22:31:09 haproxy001.test systemd[1]: Starting HAProxy Load Balancer...
Feb 04 22:31:12 haproxy001.test haproxy[5395]: [ALERT] 034/223111 (5395) : Starting frontend user_tags_27002_frontend: cannot bind socket [0.0.0.0:27002]
Feb 04 22:31:12 haproxy001.test haproxy[5395]: [ALERT] 034/223111 (5395) : Starting frontend user_tags_27006_frontend: cannot bind socket [0.0.0.0:27006]
Feb 04 22:31:12 haproxy001.test systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
Feb 04 22:31:12 haproxy001.test systemd[1]: Failed to start HAProxy Load Balancer.
Feb 04 22:31:12 haproxy001.test systemd[1]: Unit haproxy.service entered failed state.
Feb 04 22:31:12 haproxy001.test systemd[1]: haproxy.service failed.
Feb 04 22:31:13 haproxy001.test systemd[1]: haproxy.service holdoff time over, scheduling restart.
Feb 04 22:31:13 haproxy001.test systemd[1]: Stopped HAProxy Load Balancer.
Feb 04 22:31:13 haproxy001.test systemd[1]: Starting HAProxy Load Balancer...
```
###  the fllowing is haproxy.cfg
```
defaults
  maxconn 300000
  log global
  option redispatch
  option http-server-close
  timeout http-request 10s
  timeout check 10s
  timeout connect 10s
  timeout client 1m
  timeout queue 1m
  timeout server 1m
  timeout http-keep-alive 10s
  retries                 3

global
  daemon
  maxconn 300000
  pidfile /run/haproxy.pid
  stats socket /var/run/haproxy.sock mode 777 level admin expose-fd listeners
  log 127.0.0.1:514 local2
  #stats socket /run/haproxy/admin.sock mode 777 level admin expose-fd listeners
  chroot      /var/lib/haproxy
  user        root
  group       root
```

### the fllowing is systemd.service default content
```
[Unit]
Description=HAProxy Load Balancer
Documentation=man:haproxy(1)
After=syslog.target network.target

[Service]
EnvironmentFile=-/etc/sysconfig/haproxy
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/var/run/haproxy.pid"
ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $OPTIONS
ExecReload=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
SuccessExitStatus=143
Type=notify

[Install]
WantedBy=multi-user.target
```
### haproxy -vv
```
HA-Proxy version 2.0.12 2019/12/21 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_PCRE=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

what's the problem....?

**Comment by chipitsine** [comment]
are you trying to reload systemd + haproxy + dataplane api ?

https://www.mail-archive.com/haproxy@formilux.org/msg36209.html

**Comment by Kevinz857** [comment]
> are you trying to reload systemd + haproxy + dataplane api ?
> 
> https://www.mail-archive.com/haproxy@formilux.org/msg36209.html

Yep, it looks like a bug?

**Comment by chipitsine** [comment]
I'm away from that topic. I will try on weekend. Please drop a notice here if you will find something

**Comment by wlallemand** [comment]
@DanielZW 

I'm confused, I though you were not using the program section in your configuration but were running the dataplane-api separately.

Could your provide the complete logs with the startup part and the reload part, because it's incomplete and I don't understand why systemd is deciding to restart the process by itself.

Did you try to reload manually with "systemctl reload haproxy" without editing the configuration?

**Comment by Kevinz857** [comment]
@wlallemand 
Thanks for ur reply.
The purpose is ensure that the dataplane-api is always online of running the dataplane-api separately, when haproxy reload failed for some reasons.

### When I reload manually with "systemctl reload haproxy" without editing the configuration is work.
```
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: reloading (reload) since Tue 2020-02-04 22:31:54 CST; 23h ago
     Docs: man:haproxy(1)
  Process: 13712 ExecReload=/bin/kill -USR2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 5597 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5602 (haproxy);         : 5674 (haproxy)
   CGroup: /system.slice/haproxy.service
           ├─ 5602 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf 13415 6673 5612 -x /var/run/haproxy.sock
           ├─ 5612 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
           ├─ 6673 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf 5612 -x /var/run/haproxy.sock
           ├─13737 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf 13415 6673 5612 -x /var/run/haproxy.sock
            └─control
             └─5674 /usr/sbin/proxy -f /etc/haproxy/haproxy.cfg -c -q



Feb 05 21:54:31 haproxy001.test systemd[1]: Reloading HAProxy Load Balancer.
Feb 05 21:55:31 haproxy001.test haproxy[5602]: [WARNING] 035/215531 (5602) : Reexecuting Master process
Feb 05 21:55:32 haproxy001.test haproxy[5602]: [WARNING] 035/215532 (13737) : Stopping frontend GLOBAL in 0 ms.
Feb 05 21:55:32 haproxy001.test haproxy[5602]: [WARNING] 035/215532 (13737) : Stopping frontend engine_38900_frontend in 0 ms.
Feb 05 21:55:32 haproxy001.test haproxy[5602]: [WARNING] 035/215532 (13737) : Stopping frontend engine_38901_frontend in 0 ms.
Feb 05 21:55:32 haproxy001.test haproxy[5602]: [WARNING] 035/215532 (13737) : Stopping frontend engine_38902_frontend in 0 ms.
Feb 05 21:55:32 haproxy001.test systemd[1]: Reloaded HAProxy Load Balancer.
```

### And the fllowing is way of start dataplane api
```
 dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5  --log-file=/var/log/dataplaneapi/dataplaneapi.log  --log-level=trace >> /var/log/dataplaneapi/dataplaneapi.log 2>&1 &
```

I'm confused what's wrong with my configuration...

**Comment by Kevinz857** [comment]
> @DanielZW
> 
> I'm confused, I though you were not using the program section in your configuration but were running the dataplane-api separately.
> 
> Could your provide the complete logs with the startup part and the reload part, because it's incomplete and I don't understand why systemd is deciding to restart the process by itself.
> 
> Did you try to reload manually with "systemctl reload haproxy" without editing the configuration?

"I don't understand why systemd is deciding to restart the process by itself."

@wlallemand 
because when I reload  haproxy, "pause" state appear in the haproxy log  I guess.

```
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend 44609_frontend.
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend recommend_46000_frontend.
Feb 04 22:29:41 haproxy001.test haproxy[2201]: [WARNING] 034/222940 (2203) : Pausing frontend recommend_46001_frontend.
.....
Feb 04 22:29:42 haproxy001.test haproxy[2201]: [ALERT] 034/222942 (2201) : Failed to get the sockets from the old process!
.....
Feb 04 22:31:09 haproxy001.test systemd[1]: Reload failed for HAProxy Load Balancer.
Feb 04 22:31:09 haproxy001.test systemd[1]: Unit haproxy.service entered failed state.
Feb 04 22:31:09 haproxy001.test systemd[1]: haproxy.service failed.
Feb 04 22:31:09 haproxy001.test systemd[1]: haproxy.service holdoff time over, scheduling restart.
Feb 04 22:31:09 haproxy001.test systemd[1]: Stopped HAProxy Load Balancer.
Feb 04 22:31:09 haproxy001.test systemd[1]: Starting HAProxy Load Balancer...
Fe
```

**Comment by wlallemand** [comment]
> When I reload manually with "systemctl reload haproxy" without editing the configuration is work.

Ok, good to know.

>  because when I reload haproxy, "pause" state appear in the haproxy log I guess.

I still need more logs on your failed reload, from the "Reloading HAProxy Load Balancer" to the "haproxy.service holdoff time over, scheduling restart.". 

> Feb 04 22:31:12 haproxy001.test haproxy[5395]: [ALERT] 034/223111 (5395) : Starting frontend user_tags_27002_frontend: cannot bind socket [0.0.0.0:27002]
> Feb 04 22:31:12 haproxy001.test haproxy[5395]: [ALERT] 034/223111 (5395) : Starting frontend user_tags_27006_frontend: cannot bind socket [0.0.0.0:27006]

Also this part is not normal, do you have a service running on the 27002 and 27006 ports?

**Comment by capflam** [comment]
No feedback since a while. May be closed now.
