### ISSUE TITLE
Haproxy doesn't force DNS resolution on connection errors because of long hold valid resolvers option

### ISSUE THREAD

**Issue by maciejmrozinski** [haproxy/haproxy#573]
## Output of `haproxy -vv` and `uname -a`
```
HA-Proxy version 1.8.19 2019/02/11
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_ZLIB=1 USE_POLL=default USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace

Linux ThinkPad-T450 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?
```
global
	log /dev/log	local1 debug
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3

defaults
	log	global
	mode	http
	option  httplog
	option	dontlognull
        option http-keep-alive
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http


resolvers mydns
    nameserver dns1 192.168.0.164:53

    hold valid 1h

    accepted_payload_size 8192 # allow larger DNS payloads

frontend http-in
    bind *:10080
    mode http

    use_backend B3    

backend B3
    mode http

    server A backend.local:8080 check inter 1s fastinter 500ms downinter 250ms resolvers mydns init-addr none

    http-response set-header X-Upstream %si
```

## Steps to reproduce the behavior
1. Run `backend.local` service on server X (IP: 192.168.0.10)
2. Set `resolvers hold valid` option for long period (1h here) to keep connections sticked and keep-alived to one IP address, to optimize response times
3. Run haproxy, backend reports UP
4. Change `backend.local` - IP mapping on DNS server to point to another server Y (IP: 192.168.0.200)
5. Nothing happens as valid period is set to 1h (good), nothing happens because server with old IP still checks OK (good)
6. Run another instance of `backend.local` service on server Y (IP: 192.168.0.200)
7. Shutdown `backend.local` service on server X

## Actual behavior
Backend reports DOWN, haproxy doesn't ask DNS server for new IP

## Expected behavior
In my opinion haproxy should check (also docs states as it works like that) for new IP address. Quote from docs:
```
A few other events can trigger a name resolution at run time:
  - when a server's health check ends up in a connection timeout: this may be
    because the server has a new IP address. So we need to trigger a name
    resolution to know this new IP.
```
Code also states that this should work:
https://github.com/haproxy/haproxy/blob/58a522227ba3697e5701e0e7c51683dc00bcc811/src/checks.c#L698

## Do you have any idea what may have caused this?
This is not working since before real DNS resolution is made, haproxy checks DNS cache based on current time and `hold valid` period (and few other things) and the result is that cache is still valid (which is true), but with error, maybe we should force DNS resolution despite timers and periods.

## Do you have an idea how to solve the issue?
I created branch on forked repo which resolves this issue:
https://github.com/maciejmrozinski/haproxy/commit/c6684a20e2b60d9defc72da1afc9b80e612ed60e

**Comment by bedis** [comment]
Hi @maciejmrozinski 

Thanks for reporting this problem.
Can you run a tcpdump and confirm whether DNS requests are sent by HAProxy or not?

**Comment by bedis** [comment]
I have a positive answer to you :)
This isse was reported in #345 and was fixed in patch f50e1ac4442be41ed8b9b7372310d1d068b85b33, "BUG: dns: timeout resolve not applied for valid resolutions".

This has been backported in 1.8 branch and is available in version 1.8.23 and above.

This is what this patch does:

    Documentation states that the interval between 2 DNS resolution is
    driven by "timeout resolve <time>" directive.
    From a code point of view, this was applied unless the latest status of
    the resolution was VALID. In such case, "hold valid" was enforce.
    This is a bug, because "hold" timers are not here to drive how often we
    want to trigger a DNS resolution, but more how long we want to keep an
    information if the status of the resolution itself as changed.
    This avoid flapping and prevent shutting down an entire backend when a
    DNS server is not answering.

Let me know if you think this would fix your issue or not.

**Comment by maciejmrozinski** [comment]
Hi,

I cloned and builded newest master (HA-Proxy version 2.2-dev5-58a522-49 2020/04/02) and tried the scenario. I modified my configuration by setting hold valid to 5s and by adding resolve timeout with value of 1h (to keep connections alive with one server as long as possible, shorter period reconnects backend to new IP which is undesirable).

The issue still exists, on connection error the DNS resolution is not forced, but imo should be.

EDIT: Just to add more information: DNS queries are not sent, I checked my local DNS logs, and no queries are logged.

**Comment by bedis** [comment]
Hi @maciejmrozinski 

If your intention is to change the server's IP address only when this one fail, then this can't work with current implementation. Purpose of DNS is to follow-up on changes which occur in your platform.

To make it clear, `hold valid` will keep the valid state if the server is unavailable or returns some errors for the period of time mentioned.
The `timeout resolve` tells HAProxy how frequently it is supposed to run those DNS resolutions.

**Comment by vasanth-pandian** [comment]
Hi @bedis 
Just wanted to confirm the behaviour. Let's say, if i use the below configuration.

```
resolvers test_resolver
    parse-resolv-conf
    accepted_payload_size 8192
    hold valid 15m
    timeout resolve 60s
```

Case 1:
Even if my DNS Server fails, last valid resolution will be used & traffic will still flow to my backend servers for 15m. 

Case 2:
Assume no issues with my DNS server or resolution. If i add new backend servers (which gets added to DNS records automatically), since resolution is happening for every 60s, the newly added backend servers will receive traffic.
Just wanted to ensure that the newly added servers are not idle for 15m.
